import { MigrationInterface, QueryRunner } from "typeorm";

export class Init1771872983899 implements MigrationInterface {
    name = 'Init1771872983899'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "hts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "hts_number" character varying(20) NOT NULL, "version" character varying(50) NOT NULL, "indent" integer NOT NULL DEFAULT '0', "description" text NOT NULL, "unit_of_quantity" character varying(50), "unit" character varying(50), "general_rate" text, "general" text, "rate_formula" text, "rate_variables" jsonb, "is_formula_generated" boolean NOT NULL DEFAULT false, "other_rate" text, "other" text, "other_rate_formula" text, "other_rate_variables" jsonb, "is_other_formula_generated" boolean NOT NULL DEFAULT false, "special_rates" jsonb, "special" text, "chapter99" text, "chapter99_links" jsonb, "chapter99_applicable_countries" jsonb, "non_ntr_applicable_countries" jsonb, "adjusted_formula" text, "adjusted_formula_variables" jsonb, "is_adjusted_formula_generated" boolean NOT NULL DEFAULT false, "other_chapter99" text, "other_chapter99_detail" jsonb, "footnotes" text, "additional_duties" text, "quota" character varying(255), "quota2" character varying(255), "chapter" character varying(2) NOT NULL, "heading" character varying(4), "subheading" character varying(6), "statistical_suffix" character varying(10), "parent_hts_number" character varying(20), "parent_htses" jsonb, "full_description" jsonb, "is_heading" boolean NOT NULL DEFAULT false, "is_subheading" boolean NOT NULL DEFAULT false, "has_children" boolean NOT NULL DEFAULT false, "source_version" character varying(50), "import_date" TIMESTAMP, "is_active" boolean NOT NULL DEFAULT true, "confirmed" boolean NOT NULL DEFAULT false, "update_formula_comment" text, "required_review" boolean NOT NULL DEFAULT false, "required_review_comment" text, "effective_date" date, "expiration_date" date, "metadata" jsonb, "search_vector" tsvector, "embedding" vector(1536), "embedding_search_text" text, "embedding_model" character varying(50), "embedding_generated_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_efca6f12f7865e192229f218cd6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f275d908c01a4093ac441a51ef" ON "hts" ("parent_hts_number") `);
        await queryRunner.query(`CREATE INDEX "IDX_0ba756d3d3513bbf0516126396" ON "hts" ("heading") `);
        await queryRunner.query(`CREATE INDEX "IDX_59a4b0d8d9345238fc99691ad2" ON "hts" ("chapter") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_93e6f2a2f936e142ed01b07741" ON "hts" ("hts_number", "version") `);
        await queryRunner.query(`CREATE TABLE "hts_test_cases" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "hts_number" character varying(20) NOT NULL, "country" character varying(3) NOT NULL DEFAULT 'ALL', "test_name" character varying(255) NOT NULL, "description" text, "input_values" jsonb NOT NULL, "expected_output" numeric(15,4) NOT NULL, "tolerance" numeric(10,4) NOT NULL DEFAULT 0.01, "rate_type" character varying(20) NOT NULL DEFAULT 'GENERAL', "source" character varying(50) NOT NULL DEFAULT 'MANUAL', "is_active" boolean NOT NULL DEFAULT true, "priority" integer NOT NULL DEFAULT '50', "created_by" character varying(255) NOT NULL, "notes" text, "tags" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e6340fa87b4d9d1629949d59270" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8acd8cceae47d9f71dbcba824c" ON "hts_test_cases" ("country") `);
        await queryRunner.query(`CREATE INDEX "IDX_01f246f0fd1ebca76678d8da28" ON "hts_test_cases" ("hts_number") `);
        await queryRunner.query(`CREATE TABLE "hts_test_results" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "test_case_id" uuid NOT NULL, "run_id" uuid NOT NULL, "passed" boolean NOT NULL, "actual_output" numeric(15,4) NOT NULL, "expected_output" numeric(15,4) NOT NULL, "difference" numeric(15,4) NOT NULL, "percentage_error" numeric(10,4), "formula_used" text NOT NULL, "formula_source" character varying(50) NOT NULL, "execution_time_ms" integer, "error_message" text, "stack_trace" text, "input_values" jsonb NOT NULL, "executed_at" TIMESTAMP NOT NULL DEFAULT now(), "engine_version" character varying(20), "environment" character varying(20) NOT NULL DEFAULT 'test', "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_af1b95dacc022e7bfca76d9f5f4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_03f262367d3b764de47770c7b4" ON "hts_test_results" ("executed_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_06f569d0b85f6a5c11b3803f1f" ON "hts_test_results" ("passed") `);
        await queryRunner.query(`CREATE INDEX "IDX_a5b7bd9b3bdd2e056725f462cd" ON "hts_test_results" ("run_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_922e021c9a1380e147b3bf630b" ON "hts_test_results" ("test_case_id") `);
        await queryRunner.query(`CREATE TABLE "hts_tariff_history_2025" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "source_year" integer NOT NULL DEFAULT '2025', "source_dataset" character varying(30) NOT NULL DEFAULT 'tariff_data_2025', "hts8" character varying(8) NOT NULL, "brief_description" text NOT NULL, "quantity1_code" character varying(20), "quantity2_code" character varying(20), "wto_binding_code" character varying(4), "mfn_text_rate" character varying(255), "mfn_rate_type_code" character varying(20), "mfn_ad_val_rate" numeric(16,8), "mfn_specific_rate" numeric(16,8), "mfn_other_rate" numeric(16,8), "col1_special_text" character varying(255), "col1_special_mod" character varying(50), "col2_text_rate" character varying(255), "col2_rate_type_code" character varying(20), "col2_ad_val_rate" numeric(16,8), "col2_specific_rate" numeric(16,8), "col2_other_rate" numeric(16,8), "begin_effect_date" date NOT NULL, "end_effective_date" date NOT NULL, "footnote_comment" text, "additional_duty" text, "pharmaceutical_indicator" character varying(10), "dyes_indicator" character varying(10), "nepal_indicator" character varying(10), "preference_programs" jsonb NOT NULL DEFAULT '{}', "math_components" jsonb NOT NULL DEFAULT '{}', "raw_row" jsonb NOT NULL, "row_hash" character varying(64) NOT NULL, "is2026_reference" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d328e85bc39610bb12ab7a509ad" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6ab6b2a85a4295d89281347557" ON "hts_tariff_history_2025" ("end_effective_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_77df6794987c59f9cfb2c92a17" ON "hts_tariff_history_2025" ("source_year") `);
        await queryRunner.query(`CREATE INDEX "IDX_77e8583093c7d49009649ad59d" ON "hts_tariff_history_2025" ("hts8") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_193ed61ce278cad811a8637181" ON "hts_tariff_history_2025" ("source_year", "hts8", "begin_effect_date", "end_effective_date") `);
        await queryRunner.query(`CREATE TABLE "hts_stage_validation_issues" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "import_id" uuid NOT NULL, "stage_entry_id" uuid, "hts_number" character varying(20), "issue_code" character varying(50) NOT NULL, "severity" character varying(20) NOT NULL DEFAULT 'ERROR', "message" text NOT NULL, "details" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_88f4bdaf9c3ef95bcfdcc8a5187" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0ddc2ac4f7d7553c676ad9f34b" ON "hts_stage_validation_issues" ("severity") `);
        await queryRunner.query(`CREATE INDEX "IDX_d4bcb0fc143114515226a6cfe9" ON "hts_stage_validation_issues" ("stage_entry_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e7f8923bbaff00fe72b7790c5e" ON "hts_stage_validation_issues" ("import_id") `);
        await queryRunner.query(`CREATE TABLE "hts_stage_diffs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "import_id" uuid NOT NULL, "stage_entry_id" uuid, "current_hts_id" uuid, "hts_number" character varying(20) NOT NULL, "diff_type" character varying(20) NOT NULL, "diff_summary" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d610fac847a8d0f92eb9159c6e1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1e427d2642b67ffc3ef6274777" ON "hts_stage_diffs" ("diff_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_777a40f97b08644429f8dded77" ON "hts_stage_diffs" ("stage_entry_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ccf0e1294afcdd5b332480e27f" ON "hts_stage_diffs" ("import_id") `);
        await queryRunner.query(`CREATE TABLE "hts_stage_entries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "import_id" uuid NOT NULL, "source_version" character varying(50) NOT NULL, "hts_number" character varying(20) NOT NULL, "indent" integer NOT NULL DEFAULT '0', "description" text NOT NULL, "unit" character varying(50), "general_rate" text, "special" text, "other" text, "chapter99" text, "chapter" character varying(2) NOT NULL, "heading" character varying(4), "subheading" character varying(6), "statistical_suffix" character varying(10), "parent_hts_number" character varying(20), "row_hash" character varying(64) NOT NULL, "raw_item" jsonb, "normalized" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e571c47bccd5d26dfbe222cc7ef" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_177a9dd2052799f50f21a72220" ON "hts_stage_entries" ("source_version") `);
        await queryRunner.query(`CREATE INDEX "IDX_7cde7d4f3e1e95df868ca77156" ON "hts_stage_entries" ("hts_number") `);
        await queryRunner.query(`CREATE INDEX "IDX_f4c3186cbda8e030ddf01c860f" ON "hts_stage_entries" ("import_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_909e9e12dd8aa8c55c09608023" ON "hts_stage_entries" ("import_id", "hts_number") `);
        await queryRunner.query(`CREATE TABLE "hts_settings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "key" character varying(100) NOT NULL, "value" text NOT NULL, "data_type" character varying(20) NOT NULL DEFAULT 'STRING', "category" character varying(50) NOT NULL DEFAULT 'general', "description" text, "is_editable" boolean NOT NULL DEFAULT true, "is_sensitive" boolean NOT NULL DEFAULT false, "validation_rules" jsonb, "default_value" text, "last_updated_by" character varying(255), "effective_date" TIMESTAMP, "notes" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_835ebef092e3c4722a9a80a07e2" UNIQUE ("key"), CONSTRAINT "PK_b3686c84cf545169190bb703676" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_467d5a0909fa689f6b3a0929b6" ON "hts_settings" ("category") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_835ebef092e3c4722a9a80a07e" ON "hts_settings" ("key") `);
        await queryRunner.query(`CREATE TABLE "hts_import_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "source_version" character varying(50) NOT NULL, "source_url" text NOT NULL, "source_file_hash" character varying(64), "status" character varying(30) NOT NULL DEFAULT 'PENDING', "total_entries" integer NOT NULL DEFAULT '0', "imported_entries" integer NOT NULL DEFAULT '0', "updated_entries" integer NOT NULL DEFAULT '0', "skipped_entries" integer NOT NULL DEFAULT '0', "failed_entries" integer NOT NULL DEFAULT '0', "import_started_at" TIMESTAMP, "import_completed_at" TIMESTAMP, "duration_seconds" integer, "started_by" character varying(255) NOT NULL DEFAULT 'SYSTEM', "error_message" text, "error_stack" text, "failed_entries_detail" jsonb, "import_log" jsonb, "metadata" jsonb, "rollback_info" jsonb, "checkpoint" jsonb, "s3_bucket" character varying(255), "s3_key" character varying(500), "s3_file_hash" character varying(64), "job_id" character varying(100), "downloaded_at" TIMESTAMP, "download_size_bytes" bigint, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7648c567901f7a7ff0b97191244" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cc7a59dd162756f80ea7c7ae49" ON "hts_import_history" ("checkpoint") `);
        await queryRunner.query(`CREATE INDEX "IDX_07981ba7d94d264616abca9503" ON "hts_import_history" ("job_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_47dc86f5c1ec1a2419c9bdbc14" ON "hts_import_history" ("import_started_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_ba1499ab3c7580e44147eb51da" ON "hts_import_history" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_2a8c844d6b4da3adcc4befa189" ON "hts_import_history" ("source_version") `);
        await queryRunner.query(`CREATE TABLE "hts_formula_candidates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "hts_number" character varying(20) NOT NULL, "country_code" character varying(3) NOT NULL DEFAULT 'ALL', "formula_type" character varying(30) NOT NULL, "current_formula" text, "proposed_formula" text NOT NULL, "proposed_variables" jsonb, "confidence" numeric(5,4) NOT NULL, "reasoning" text NOT NULL, "status" character varying(20) NOT NULL DEFAULT 'PENDING', "review_comment" text, "reviewed_by" character varying(255), "reviewed_at" TIMESTAMP, "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_110183950d7267887ce8e3a4b25" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b9e53ef66cb5d5821cecbe5d95" ON "hts_formula_candidates" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_5e11c07c6ead521d6eeb5ff6eb" ON "hts_formula_candidates" ("confidence") `);
        await queryRunner.query(`CREATE INDEX "IDX_f1c5c43dd3b79e649eca2e28db" ON "hts_formula_candidates" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_52b4f0d506c903cc197ae4a2e5" ON "hts_formula_candidates" ("hts_number") `);
        await queryRunner.query(`CREATE TABLE "hts_formula_updates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "hts_number" character varying(20) NOT NULL, "country_code" character varying(4) NOT NULL DEFAULT 'ALL', "formula_type" character varying(30) NOT NULL, "formula" text NOT NULL, "formula_variables" jsonb, "comment" text, "active" boolean NOT NULL DEFAULT true, "carryover" boolean NOT NULL DEFAULT true, "override_extra_tax" boolean NOT NULL DEFAULT false, "update_version" character varying(50) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b3fc398db233160723d97cedba3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d6dea3fbb3cc33e44794956869" ON "hts_formula_updates" ("hts_number", "country_code", "formula_type") `);
        await queryRunner.query(`CREATE TABLE "hts_extra_taxes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tax_code" character varying(50) NOT NULL, "tax_name" character varying(255) NOT NULL, "description" text, "hts_number" character varying(20), "hts_chapter" character varying(2), "country_code" character varying(3) NOT NULL DEFAULT 'ALL', "extra_rate_type" character varying(50) NOT NULL DEFAULT 'ADD_ON', "rate_text" character varying(255) NOT NULL, "rate_formula" text, "minimum_amount" numeric(15,4), "maximum_amount" numeric(15,4), "is_percentage" boolean NOT NULL DEFAULT false, "apply_to" character varying(20) NOT NULL DEFAULT 'VALUE', "conditions" jsonb, "priority" integer NOT NULL DEFAULT '50', "is_active" boolean NOT NULL DEFAULT true, "effective_date" date, "expiration_date" date, "legal_reference" text, "notes" text, "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a1fda55ae78228065340198e42a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_50c08ba4ea3023ad32b23b75e2" ON "hts_extra_taxes" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_828743e7b996d8d013283f4647" ON "hts_extra_taxes" ("tax_code") `);
        await queryRunner.query(`CREATE INDEX "IDX_9fb329c9c48a32c253835b8b00" ON "hts_extra_taxes" ("hts_number") `);
        await queryRunner.query(`CREATE TABLE "external_provider_formulas" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "provider" character varying(32) NOT NULL, "hts_number" character varying(20) NOT NULL, "country_code" character varying(3) NOT NULL, "entry_date" date NOT NULL, "mode_of_transport" character varying(16) NOT NULL DEFAULT 'OCEAN', "input_context" jsonb NOT NULL, "context_hash" character varying(64) NOT NULL, "formula_raw" text, "formula_normalized" text, "formula_components" jsonb, "output_breakdown" jsonb, "extraction_method" character varying(16) NOT NULL DEFAULT 'NETWORK', "extraction_confidence" numeric(5,4) NOT NULL DEFAULT '0', "parser_version" character varying(32) NOT NULL DEFAULT 'v1', "source_url" text NOT NULL, "evidence" jsonb, "review_status" character varying(20) NOT NULL DEFAULT 'PENDING', "review_decision_comment" text, "reviewed_by" character varying(255), "reviewed_at" TIMESTAMP, "published_formula_update_id" uuid, "published_by" character varying(255), "published_at" TIMESTAMP, "publish_metadata" jsonb, "observed_at" TIMESTAMP NOT NULL DEFAULT now(), "observed_by" character varying(255), "is_latest" boolean NOT NULL DEFAULT true, "superseded_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4cfa4f338533f1314324c4a2004" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_ext_provider_formula_latest_context" ON "external_provider_formulas" ("provider", "context_hash", "is_latest") WHERE "is_latest" = true`);
        await queryRunner.query(`CREATE INDEX "IDX_ext_provider_formula_review_status" ON "external_provider_formulas" ("review_status") `);
        await queryRunner.query(`CREATE INDEX "IDX_ext_provider_formula_context" ON "external_provider_formulas" ("provider", "context_hash") `);
        await queryRunner.query(`CREATE INDEX "IDX_ext_provider_formula_lookup" ON "external_provider_formulas" ("provider", "hts_number", "country_code", "entry_date") `);
        await queryRunner.query(`CREATE TABLE "calculation_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "calculation_id" character varying(100) NOT NULL, "organization_id" uuid NOT NULL, "user_id" uuid, "scenario_id" uuid, "inputs" jsonb NOT NULL, "base_duty" numeric(18,2) NOT NULL, "additional_tariffs" numeric(18,2) NOT NULL DEFAULT '0', "total_taxes" numeric(18,2) NOT NULL DEFAULT '0', "total_duty" numeric(18,2) NOT NULL, "landed_cost" numeric(18,2) NOT NULL, "breakdown" jsonb NOT NULL, "trade_agreement_info" jsonb, "compliance_warnings" jsonb, "hts_version" character varying(50) NOT NULL, "rule_version" character varying(50), "engine_version" character varying(50) NOT NULL, "formula_used" character varying(1000), "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_2d1b868dd95af635845525ce873" UNIQUE ("calculation_id"), CONSTRAINT "PK_29e4e767a26d2ddd26a2471a21c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_274df14b2a2b00d760f6560cb1" ON "calculation_history" ("organization_id", "created_at") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_2d1b868dd95af635845525ce87" ON "calculation_history" ("calculation_id") `);
        await queryRunner.query(`CREATE TABLE "organizations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "plan" character varying(50) NOT NULL DEFAULT 'FREE', "is_active" boolean NOT NULL DEFAULT true, "settings" jsonb, "usage_quotas" jsonb, "current_usage" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6b031fcd0863e3f6b44230163f9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9b7ca6d30b94fef571cff87688" ON "organizations" ("name") `);
        await queryRunner.query(`CREATE TABLE "api_keys" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "key_hash" character varying(64) NOT NULL, "key_prefix" character varying(20) NOT NULL, "name" character varying(255) NOT NULL, "description" text, "organization_id" uuid NOT NULL, "environment" character varying(10) NOT NULL, "permissions" jsonb NOT NULL, "rate_limit_per_minute" integer NOT NULL DEFAULT '60', "rate_limit_per_day" integer NOT NULL DEFAULT '10000', "is_active" boolean NOT NULL DEFAULT true, "expires_at" TIMESTAMP, "last_used_at" TIMESTAMP, "ip_whitelist" jsonb, "allowed_origins" jsonb, "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" uuid, CONSTRAINT "UQ_57384430aa1959f4578046c9b81" UNIQUE ("key_hash"), CONSTRAINT "PK_5c8a79801b44bd27b79228e1dad" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_323a31abf1de12c7bb2d74412c" ON "api_keys" ("organization_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_0c81d2fda86d67e3b63d9743f2" ON "api_keys" ("organization_id", "is_active") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_57384430aa1959f4578046c9b8" ON "api_keys" ("key_hash") `);
        await queryRunner.query(`CREATE TABLE "widget_configs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "widget_id" character varying(100) NOT NULL, "name" character varying(255) NOT NULL, "organization_id" uuid NOT NULL, "api_key_id" uuid NOT NULL, "widget_type" character varying(50) NOT NULL, "allowed_domains" jsonb NOT NULL, "styling" jsonb, "features" jsonb NOT NULL, "defaults" jsonb, "labels" jsonb, "is_active" boolean NOT NULL DEFAULT true, "analytics_enabled" boolean NOT NULL DEFAULT true, "rate_limit_per_day" integer NOT NULL DEFAULT '1000', "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" uuid, CONSTRAINT "UQ_add42b564628399d7796abc4c8a" UNIQUE ("widget_id"), CONSTRAINT "PK_954cff3fc6c58071a2b75e3da39" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_de85aab71cd538c95c408bd395" ON "widget_configs" ("organization_id", "is_active") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_add42b564628399d7796abc4c8" ON "widget_configs" ("widget_id") `);
        await queryRunner.query(`CREATE TABLE "widget_sessions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "session_id" character varying(100) NOT NULL, "widget_config_id" uuid NOT NULL, "widget_id" character varying(100) NOT NULL, "organization_id" uuid NOT NULL, "referrer" character varying(500) NOT NULL, "page_url" character varying(1000) NOT NULL, "user_agent" character varying(500), "client_ip" character varying(45), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "ended_at" TIMESTAMP, "interaction_count" integer NOT NULL DEFAULT '0', "interactions" jsonb, "duration_seconds" integer, "metadata" jsonb, CONSTRAINT "UQ_5f466cf71c3b799322585b2eec8" UNIQUE ("session_id"), CONSTRAINT "PK_6071d01fbee6f7e8118ed9c8d9d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_5f466cf71c3b799322585b2eec" ON "widget_sessions" ("session_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_62360f6359a70e5fbca6b89e39" ON "widget_sessions" ("widget_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "onboarding_templates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "description" text, "template_type" character varying(50) NOT NULL, "schema" jsonb NOT NULL, "sample_data" jsonb, "validation_rules" text, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3d92c823abe29a6a0ad7ac25632" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6b6cd716bfedee40ea98a1bae6" ON "onboarding_templates" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_8dc0371ea3f890340dd0ed248c" ON "onboarding_templates" ("template_type") `);
        await queryRunner.query(`CREATE TABLE "onboarding_progress" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "user_id" uuid NOT NULL, "persona" character varying(50) NOT NULL, "current_step" character varying(50) NOT NULL, "completed_steps" jsonb NOT NULL DEFAULT '{}', "wizard_data" jsonb, "is_complete" boolean NOT NULL DEFAULT false, "completed_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_070eb6e4f3132f9d7f29651aa3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_24f158c08586f16fc114147688" ON "onboarding_progress" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_4ec25329691c172d07022d2ae2" ON "onboarding_progress" ("organization_id") `);
        await queryRunner.query(`CREATE TABLE "product_classifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "product_name" character varying(500) NOT NULL, "description" text, "suggested_hts" character varying(20), "confirmed_hts" character varying(20), "status" character varying(50) NOT NULL DEFAULT 'DRAFT', "confidence" numeric(5,2), "ai_suggestions" jsonb, "attributes" jsonb, "created_by" character varying(255), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_55b843567b7b2dab9ceeb455e57" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5bdcebcb22a82f7a9647acc98d" ON "product_classifications" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_f8d088f75ecdc169397b949275" ON "product_classifications" ("organization_id") `);
        await queryRunner.query(`CREATE TABLE "lookup_conversation_sessions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" character varying(100), "user_profile" character varying(200), "status" character varying(30) NOT NULL DEFAULT 'active', "context_json" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d14c8f58e5f801f7d4871d37846" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_66e33a0c2623e71aed96aa6409" ON "lookup_conversation_sessions" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_8650a9ef31234b8d2d7d708f99" ON "lookup_conversation_sessions" ("organization_id") `);
        await queryRunner.query(`CREATE TABLE "lookup_conversation_messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "session_id" uuid NOT NULL, "role" character varying(20) NOT NULL, "content_json" jsonb NOT NULL, "tool_trace_json" jsonb, "token_usage" jsonb, "status" character varying(20) NOT NULL DEFAULT 'complete', "error_message" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2079a79cf2e00b32cf58d8d6ca7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bd5e4db5ee0a20d404f0ecd2ff" ON "lookup_conversation_messages" ("role") `);
        await queryRunner.query(`CREATE INDEX "IDX_8fe2362cd9682152015795abfb" ON "lookup_conversation_messages" ("session_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "api_usage" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid, "ip_address" character varying(45), "endpoint" character varying(100) NOT NULL, "date" date NOT NULL, "count" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_41ae86fbe940afcecd47221edb9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e6ce664b504a300f1760ae7eb7" ON "api_usage" ("ip_address", "date", "endpoint") `);
        await queryRunner.query(`CREATE INDEX "IDX_af45606581262d2382516b0c55" ON "api_usage" ("organization_id", "date", "endpoint") `);
        await queryRunner.query(`CREATE TABLE "lookup_conversation_feedback" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "session_id" uuid NOT NULL, "message_id" uuid, "is_correct" boolean NOT NULL, "chosen_hts" character varying(20), "comment" text, "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1a1c129b424eafbb0682ac4b63b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f702048eadb1548713d5cfa620" ON "lookup_conversation_feedback" ("is_correct") `);
        await queryRunner.query(`CREATE INDEX "IDX_9c15784c5886c071dd2b0bb39c" ON "lookup_conversation_feedback" ("session_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "hts_documents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "year" integer NOT NULL, "chapter" character varying(3) NOT NULL, "type" character varying(50) NOT NULL DEFAULT 'GENERAL', "source_version" character varying(50) NOT NULL, "url" text NOT NULL, "pdf_buffer" bytea, "parsed_text" text, "num_pages" integer, "status" character varying(20) NOT NULL DEFAULT 'PENDING', "error_message" text, "hash" character varying(64), "file_size" integer, "downloaded_at" TIMESTAMP, "parsed_at" TIMESTAMP, "processed_at" TIMESTAMP, "is_parsed" boolean NOT NULL DEFAULT false, "metadata" jsonb, "checkpoint" jsonb, "s3_bucket" character varying(255), "s3_key" character varying(500), "s3_file_hash" character varying(64), "job_id" character varying(100), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_59f395f47c4737dd0576835e4e5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1a77c375eaf4080467b356057c" ON "hts_documents" ("checkpoint") `);
        await queryRunner.query(`CREATE INDEX "IDX_7a8dc27c3c19f76bff6be0ecc6" ON "hts_documents" ("job_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_1145d957e031494b94e68021ce" ON "hts_documents" ("year", "chapter", "type") `);
        await queryRunner.query(`CREATE TABLE "knowledge_chunks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "document_id" uuid NOT NULL, "chunk_index" integer NOT NULL, "content" text NOT NULL, "token_count" integer NOT NULL, "embedding" vector(1536), "embedding_status" character varying(20) NOT NULL DEFAULT 'PENDING', "embedding_generated_at" TIMESTAMP, "error_message" text, "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_81af684d79d321813c41019a5cd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bdb0c523efff746aa871147aae" ON "knowledge_chunks" ("embedding_status") `);
        await queryRunner.query(`CREATE INDEX "IDX_a89c759be5f9fcd1afd18906c0" ON "knowledge_chunks" ("chunk_index") `);
        await queryRunner.query(`CREATE INDEX "IDX_2089ee83745a2f45c4f97faf2a" ON "knowledge_chunks" ("document_id") `);
        await queryRunner.query(`CREATE TABLE "hts_note_embeddings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "note_id" uuid NOT NULL, "embedding" vector(1536) NOT NULL, "search_text" text NOT NULL, "search_vector" tsvector, "model" character varying(50) NOT NULL DEFAULT 'text-embedding-3-small', "generated_at" TIMESTAMP NOT NULL DEFAULT now(), "is_current" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_a66723be2c5dbc14f9e94998345" UNIQUE ("note_id"), CONSTRAINT "REL_a66723be2c5dbc14f9e9499834" UNIQUE ("note_id"), CONSTRAINT "PK_86566f7fb3ab7f43fa1f8859d78" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_60887cda9cf0c783225f0040ce" ON "hts_note_embeddings" ("is_current") `);
        await queryRunner.query(`CREATE TABLE "hts_note_rates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "note_id" uuid NOT NULL, "rate_text" text NOT NULL, "formula" text, "rate_type" character varying(50) NOT NULL, "variables" jsonb, "confidence" numeric(5,2), "verified" boolean NOT NULL DEFAULT false, "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3a3cdbddcfe9f40da25f98cc00c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f34b1b63eeea17b105b4c273f4" ON "hts_note_rates" ("note_id") `);
        await queryRunner.query(`CREATE TABLE "hts_notes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "document_id" uuid NOT NULL, "chapter" character varying(3) NOT NULL, "type" character varying(50) NOT NULL DEFAULT 'ADDITIONAL_US_NOTE', "note_number" character varying(20) NOT NULL, "title" text, "content" text NOT NULL, "scope" text, "year" integer NOT NULL, "has_rate" boolean NOT NULL DEFAULT false, "extracted_data" jsonb, "confidence" numeric(5,2), "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_674be482aedd113f6cfda38603e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7519b107f3c5d023a64277b027" ON "hts_notes" ("year", "chapter", "note_number") `);
        await queryRunner.query(`CREATE INDEX "IDX_a39683035c39b5c81a27d5ce89" ON "hts_notes" ("year", "chapter", "type", "note_number") `);
        await queryRunner.query(`CREATE INDEX "IDX_d4d58354c01ae6a638b01681fe" ON "hts_notes" ("year", "type") `);
        await queryRunner.query(`CREATE INDEX "IDX_14c0130b2ae624ad184bd8aeed" ON "hts_notes" ("type", "chapter", "note_number") `);
        await queryRunner.query(`CREATE TABLE "hts_note_references" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "hts_number" character varying(20) NOT NULL, "note_id" uuid NOT NULL, "reference_text" text NOT NULL, "source_column" character varying(20) NOT NULL, "year" integer NOT NULL, "active" boolean NOT NULL DEFAULT true, "resolution_method" character varying(50), "confidence" numeric(5,2), "resolved_formula" text, "is_resolved" boolean NOT NULL DEFAULT false, "resolution_metadata" jsonb, "resolved_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5b55a416d51f98843b26fca0bb7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_25b8340ab939226a9fa05e4391" ON "hts_note_references" ("hts_number", "note_id", "source_column", "year") `);
        await queryRunner.query(`CREATE INDEX "IDX_017e79432a698f47e2f3973e03" ON "hts_note_references" ("hts_number", "year") `);
        await queryRunner.query(`CREATE INDEX "IDX_7072b9dacca5fe1d013cb557da" ON "hts_note_references" ("hts_number", "note_id") `);
        await queryRunner.query(`CREATE TABLE "country_configs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "country_code" character varying(2) NOT NULL, "name" character varying(100) NOT NULL, "currency_code" character varying(3) NOT NULL, "tariff_system" character varying(10) NOT NULL, "locale_settings" jsonb NOT NULL, "tax_config" jsonb NOT NULL, "trade_agreements" jsonb NOT NULL DEFAULT '[]', "data_sources" jsonb, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_03f8a5d7a29c1625820ca6cde06" UNIQUE ("country_code"), CONSTRAINT "PK_a881e4e3a05bc586039329ae656" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9ca809344746f624026e2f2eae" ON "country_configs" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_03f8a5d7a29c1625820ca6cde0" ON "country_configs" ("country_code") `);
        await queryRunner.query(`CREATE TABLE "vision_analysis" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" character varying(255) NOT NULL, "image_hash" character varying(64) NOT NULL, "source_url" character varying(2000), "analysis_result" jsonb NOT NULL, "model_used" character varying(50) NOT NULL, "processing_time_ms" integer NOT NULL, "image_size_bytes" integer NOT NULL, "image_format" character varying(50) NOT NULL, "tokens_used" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_25f92b8f661745f2b6cf1909299" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3599f6a5eef7b7c6fc480caf53" ON "vision_analysis" ("image_hash") `);
        await queryRunner.query(`CREATE INDEX "IDX_a9ccb235cd22d6ebc1d8d767c4" ON "vision_analysis" ("organization_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "scraping_metadata" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" character varying(255) NOT NULL, "url" character varying(2000) NOT NULL, "url_hash" character varying(64) NOT NULL, "method" character varying(20) NOT NULL, "vision_used" boolean NOT NULL DEFAULT false, "status_code" integer NOT NULL, "scraped_data" jsonb, "processing_time_ms" integer NOT NULL, "error_message" character varying(500), "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7efea6b7cd8379315b847375c32" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7e2940ff5584fb7dea4555230d" ON "scraping_metadata" ("url_hash") `);
        await queryRunner.query(`CREATE INDEX "IDX_5f078e0aa6aa2980047d888b9e" ON "scraping_metadata" ("organization_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "extension_feedback" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" character varying(255) NOT NULL, "product_id" character varying(255) NOT NULL, "field" character varying(100) NOT NULL, "original_value" jsonb, "corrected_value" jsonb, "user_comment" text, "user_agent" character varying(500), "page_url" character varying(1000), "user_id" character varying(255), "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b160aad0787347d8ebf9a8ba2ba" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3ddddeaec6465c669dcc32aba2" ON "extension_feedback" ("product_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_523a3edcea18b308ceb8b671b9" ON "extension_feedback" ("organization_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "export_templates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid, "name" character varying(100) NOT NULL, "description" character varying(255), "template_type" character varying(50) NOT NULL, "field_mapping" jsonb NOT NULL, "format_options" jsonb, "is_system" boolean NOT NULL DEFAULT false, "is_active" boolean NOT NULL DEFAULT true, "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3777207cd282bfec6bd0261d5bc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c72ab72ad43c72543ea3e1dc99" ON "export_templates" ("is_system") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_33678998322f0747aea098a47e" ON "export_templates" ("organization_id", "name") `);
        await queryRunner.query(`CREATE TABLE "export_jobs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "created_by" uuid NOT NULL, "template" character varying(50) NOT NULL, "format" character varying(20) NOT NULL, "filters" jsonb, "status" character varying(20) NOT NULL DEFAULT 'pending', "file_url" character varying, "file_size" bigint, "record_count" integer NOT NULL DEFAULT '0', "processed_records" integer NOT NULL DEFAULT '0', "failed_records" integer NOT NULL DEFAULT '0', "error" text, "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "completed_at" TIMESTAMP, "expires_at" TIMESTAMP, CONSTRAINT "PK_3044ce6f1c6af24058ee609e063" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3b6aa9ca07be1b4f53b75bf467" ON "export_jobs" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_0032aa6713d64c5601ae5412b1" ON "export_jobs" ("organization_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "data_completeness_checks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "resource_type" character varying(50) NOT NULL, "resource_id" uuid NOT NULL, "overall_score" numeric(5,2) NOT NULL, "is_export_ready" boolean NOT NULL DEFAULT false, "issues" jsonb NOT NULL, "completeness" jsonb, "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6d46e188c13d8cd8fb6dc3d1134" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_38a3037d2dcc8bd09c78e7a521" ON "data_completeness_checks" ("resource_type", "resource_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f03cb632d6211fa6d5d41793bb" ON "data_completeness_checks" ("organization_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "connector_sync_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "connector_id" uuid NOT NULL, "sync_type" character varying(50) NOT NULL, "status" character varying(50) NOT NULL, "items_processed" integer NOT NULL DEFAULT '0', "items_succeeded" integer NOT NULL DEFAULT '0', "items_failed" integer NOT NULL DEFAULT '0', "started_at" TIMESTAMP NOT NULL, "completed_at" TIMESTAMP, "duration_ms" integer, "errors" jsonb, "summary" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e065007b1cb9ada357c32b99a65" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7e502e476a12b2abab2b0f7269" ON "connector_sync_logs" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_813ba8b85c38d2243b5b71c772" ON "connector_sync_logs" ("connector_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "connectors" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "connector_type" character varying(50) NOT NULL, "name" character varying(100) NOT NULL, "description" text, "config" jsonb NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "status" character varying(50) NOT NULL DEFAULT 'disconnected', "last_sync_at" TIMESTAMP, "last_error" text, "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c1334e2a68a8de86d1732a8e3fb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b6aae189e315d97a6fbd5a6f38" ON "connectors" ("connector_type", "is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_cbd8a4118ed5618028c7f69a00" ON "connectors" ("organization_id") `);
        await queryRunner.query(`CREATE TABLE "trade_agreements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(100) NOT NULL, "name" character varying(255) NOT NULL, "description" text, "countries" jsonb NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "effective_date" date, "expiry_date" date, "rules" jsonb, "documentation_url" character varying(500), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_6b03144e4b0705d9239d3b990e1" UNIQUE ("code"), CONSTRAINT "PK_a7322066858dbb0b2d15cba6d16" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "trade_agreement_eligibility" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "hts_number" character varying(50) NOT NULL, "trade_agreement_code" character varying(100) NOT NULL, "is_eligible" boolean NOT NULL DEFAULT true, "preferential_rate" numeric(5,2), "rate_type" character varying(50), "origin_requirements" text, "certificate_required" boolean NOT NULL DEFAULT false, "certificate_type" character varying(255), "additional_conditions" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_65c3ca616c7431250ed76817678" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9dcab0dbf595191c4724988b56" ON "trade_agreement_eligibility" ("hts_number", "trade_agreement_code") `);
        await queryRunner.query(`CREATE TABLE "calculation_scenarios" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "description" text, "organization_id" uuid NOT NULL, "user_id" uuid, "hts_number" character varying(50) NOT NULL, "country_of_origin" character varying(100) NOT NULL, "declared_value" numeric(18,2) NOT NULL, "currency" character varying(3) NOT NULL DEFAULT 'USD', "weight_kg" numeric(10,4), "quantity" integer, "quantity_unit" character varying(50), "additional_inputs" jsonb, "trade_agreement" character varying(50), "claim_preferential" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c26227bbacf62922fc58bb86045" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_dd508eaabff6c38a0f25967918" ON "calculation_scenarios" ("organization_id") `);
        await queryRunner.query(`CREATE TABLE "usage_records" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "subscription_id" uuid, "metric_name" character varying(100) NOT NULL, "quantity" integer NOT NULL, "timestamp" TIMESTAMP NOT NULL, "stripe_usage_record_id" character varying(255), "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e511cf9f7dc53851569f87467a5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4733c4313650f4e34a8396599e" ON "usage_records" ("subscription_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b6dacd2c81f576322e792bb526" ON "usage_records" ("organization_id", "metric_name", "timestamp") `);
        await queryRunner.query(`CREATE TABLE "credit_purchases" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "stripe_session_id" character varying(255) NOT NULL, "stripe_payment_intent_id" character varying(255), "credits" integer NOT NULL, "amount" numeric(10,2) NOT NULL, "currency" character varying(3) NOT NULL DEFAULT 'USD', "status" character varying(50) NOT NULL DEFAULT 'pending', "return_url" text NOT NULL, "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "completed_at" TIMESTAMP, CONSTRAINT "PK_89d96f2901d625d5879c1bc6f47" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ba3b1054ab30afce50760e8838" ON "credit_purchases" ("stripe_session_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_932e7ec556c8c0af3333c8f7b0" ON "credit_purchases" ("organization_id", "status") `);
        await queryRunner.query(`CREATE TABLE "credit_balances" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "balance" integer NOT NULL DEFAULT '0', "lifetime_purchased" integer NOT NULL DEFAULT '0', "lifetime_used" integer NOT NULL DEFAULT '0', "last_purchase_at" TIMESTAMP, "last_used_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b9f1be6c9f3f23c5716fa7d8545" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_2c5b34b1029a5ec187a07e3f1f" ON "credit_balances" ("organization_id") `);
        await queryRunner.query(`CREATE TABLE "invoices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "subscription_id" uuid, "stripe_invoice_id" character varying(255) NOT NULL, "stripe_customer_id" character varying(255) NOT NULL, "invoice_number" character varying(100), "status" character varying(50) NOT NULL, "subtotal" numeric(10,2) NOT NULL, "tax" numeric(10,2) NOT NULL, "total" numeric(10,2) NOT NULL, "currency" character varying(3) NOT NULL, "period_start" TIMESTAMP NOT NULL, "period_end" TIMESTAMP NOT NULL, "due_date" TIMESTAMP, "paid_at" TIMESTAMP, "hosted_invoice_url" character varying(500), "invoice_pdf" character varying(500), "line_items" jsonb, "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_668cef7c22a427fd822cc1be3ce" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ac0f09364e3701d9ed35435288" ON "invoices" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_0ddf8494c8665a57c670287ccd" ON "invoices" ("stripe_invoice_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b5e3ce8c220cbbebf5272c3bfa" ON "invoices" ("organization_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "subscriptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "stripe_subscription_id" character varying(255) NOT NULL, "stripe_customer_id" character varying(255) NOT NULL, "plan" character varying(50) NOT NULL, "status" character varying(50) NOT NULL, "amount" numeric(10,2) NOT NULL, "currency" character varying(3) NOT NULL, "interval" character varying(20) NOT NULL, "current_period_start" TIMESTAMP, "current_period_end" TIMESTAMP, "cancel_at" TIMESTAMP, "cancel_at_period_end" boolean NOT NULL DEFAULT false, "trial_end" TIMESTAMP, "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a87248d73155605cf782be9ee5e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6ccf973355b70645eff37774de" ON "subscriptions" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_3a2d09d943f39912a01831a927" ON "subscriptions" ("stripe_subscription_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9ea1509175fa294fc64d43a9fe" ON "subscriptions" ("organization_id") `);
        await queryRunner.query(`CREATE TABLE "auto_topup_configs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "trigger_threshold" integer NOT NULL DEFAULT '5', "recharge_amount" integer NOT NULL DEFAULT '20', "monthly_spending_cap" numeric(10,2), "current_month_spent" numeric(10,2) NOT NULL DEFAULT '0', "current_month" integer NOT NULL DEFAULT '1', "current_year" integer NOT NULL DEFAULT '2026', "stripe_payment_method_id" character varying(255), "stripe_customer_id" character varying(255), "enabled" boolean NOT NULL DEFAULT true, "email_notifications" boolean NOT NULL DEFAULT true, "last_triggered_at" TIMESTAMP, "total_auto_purchases" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_af1714d3b532d1e026a966ef8d9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_38baa0d834f93345a053c8202d" ON "auto_topup_configs" ("organization_id") `);
        await queryRunner.query(`CREATE TABLE "roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(50) NOT NULL, "description" character varying(255), "permissions" jsonb NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_648e3f5447f725579d7d4ffdfb7" UNIQUE ("name"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_648e3f5447f725579d7d4ffdfb" ON "roles" ("name") `);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying(255) NOT NULL, "password" character varying(255) NOT NULL, "first_name" character varying(100) NOT NULL, "last_name" character varying(100) NOT NULL, "organization_id" uuid NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "email_verified" boolean NOT NULL DEFAULT false, "last_login_at" TIMESTAMP, "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_21a659804ed7bf61eb91688dea" ON "users" ("organization_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE TABLE "api_usage_metrics" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "api_key_id" uuid NOT NULL, "organization_id" uuid NOT NULL, "timestamp" TIMESTAMP NOT NULL, "endpoint" character varying(255) NOT NULL, "method" character varying(10) NOT NULL, "status_code" integer NOT NULL, "response_time_ms" integer NOT NULL, "request_size_bytes" integer, "response_size_bytes" integer, "client_ip" character varying(45), "user_agent" character varying(500), "error_message" text, "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4b067356755c6a885e21c94a36f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d7c0e0f0cd7fe8916d7ef6f10f" ON "api_usage_metrics" ("api_key_id", "endpoint", "timestamp") `);
        await queryRunner.query(`CREATE INDEX "IDX_70767197fa888fa7aa8930e7ed" ON "api_usage_metrics" ("organization_id", "timestamp") `);
        await queryRunner.query(`CREATE INDEX "IDX_5cee2ae4c3aacd99c17d1cebbb" ON "api_usage_metrics" ("api_key_id", "timestamp") `);
        await queryRunner.query(`CREATE TABLE "api_usage_summaries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "api_key_id" uuid NOT NULL, "organization_id" uuid NOT NULL, "date" date NOT NULL, "total_requests" integer NOT NULL DEFAULT '0', "successful_requests" integer NOT NULL DEFAULT '0', "failed_requests" integer NOT NULL DEFAULT '0', "avg_response_time_ms" numeric(10,2) NOT NULL DEFAULT '0', "total_data_bytes" bigint NOT NULL DEFAULT '0', "endpoint_breakdown" jsonb, "status_breakdown" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL, CONSTRAINT "PK_b6875b8c4d7de9e5ac41f125ee1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_af582ae2b7d0d2df8d5637db89" ON "api_usage_summaries" ("organization_id", "date") `);
        await queryRunner.query(`CREATE INDEX "IDX_02ede4aec416291e538673b343" ON "api_usage_summaries" ("api_key_id", "date") `);
        await queryRunner.query(`CREATE TABLE "user_roles" ("user_id" uuid NOT NULL, "role_id" uuid NOT NULL, CONSTRAINT "PK_23ed6f04fe43066df08379fd034" PRIMARY KEY ("user_id", "role_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_87b8888186ca9769c960e92687" ON "user_roles" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b23c65e50a758245a33ee35fda" ON "user_roles" ("role_id") `);
        await queryRunner.query(`ALTER TABLE "hts_test_results" ADD CONSTRAINT "FK_922e021c9a1380e147b3bf630bc" FOREIGN KEY ("test_case_id") REFERENCES "hts_test_cases"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "api_keys" ADD CONSTRAINT "FK_a283bdef18876e525aefaec042f" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "widget_configs" ADD CONSTRAINT "FK_c55c70aebb84dc08bc16d962348" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "widget_configs" ADD CONSTRAINT "FK_b30e55338d96b70fa88388d8f96" FOREIGN KEY ("api_key_id") REFERENCES "api_keys"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "widget_sessions" ADD CONSTRAINT "FK_aad45892f1ec6f0023ae7c8f654" FOREIGN KEY ("widget_config_id") REFERENCES "widget_configs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "knowledge_chunks" ADD CONSTRAINT "FK_2089ee83745a2f45c4f97faf2a5" FOREIGN KEY ("document_id") REFERENCES "hts_documents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hts_note_embeddings" ADD CONSTRAINT "FK_a66723be2c5dbc14f9e94998345" FOREIGN KEY ("note_id") REFERENCES "hts_notes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hts_note_rates" ADD CONSTRAINT "FK_f34b1b63eeea17b105b4c273f40" FOREIGN KEY ("note_id") REFERENCES "hts_notes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hts_notes" ADD CONSTRAINT "FK_6ee464e145bf6c67aa60d92dc85" FOREIGN KEY ("document_id") REFERENCES "hts_documents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hts_note_references" ADD CONSTRAINT "FK_4f1a3f1a9cc0dfeced9f55af975" FOREIGN KEY ("note_id") REFERENCES "hts_notes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_21a659804ed7bf61eb91688dea7" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "api_usage_metrics" ADD CONSTRAINT "FK_e54ec1fb41ba242a73fa158eef2" FOREIGN KEY ("api_key_id") REFERENCES "api_keys"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_87b8888186ca9769c960e926870" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_b23c65e50a758245a33ee35fda1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_b23c65e50a758245a33ee35fda1"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_87b8888186ca9769c960e926870"`);
        await queryRunner.query(`ALTER TABLE "api_usage_metrics" DROP CONSTRAINT "FK_e54ec1fb41ba242a73fa158eef2"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_21a659804ed7bf61eb91688dea7"`);
        await queryRunner.query(`ALTER TABLE "hts_note_references" DROP CONSTRAINT "FK_4f1a3f1a9cc0dfeced9f55af975"`);
        await queryRunner.query(`ALTER TABLE "hts_notes" DROP CONSTRAINT "FK_6ee464e145bf6c67aa60d92dc85"`);
        await queryRunner.query(`ALTER TABLE "hts_note_rates" DROP CONSTRAINT "FK_f34b1b63eeea17b105b4c273f40"`);
        await queryRunner.query(`ALTER TABLE "hts_note_embeddings" DROP CONSTRAINT "FK_a66723be2c5dbc14f9e94998345"`);
        await queryRunner.query(`ALTER TABLE "knowledge_chunks" DROP CONSTRAINT "FK_2089ee83745a2f45c4f97faf2a5"`);
        await queryRunner.query(`ALTER TABLE "widget_sessions" DROP CONSTRAINT "FK_aad45892f1ec6f0023ae7c8f654"`);
        await queryRunner.query(`ALTER TABLE "widget_configs" DROP CONSTRAINT "FK_b30e55338d96b70fa88388d8f96"`);
        await queryRunner.query(`ALTER TABLE "widget_configs" DROP CONSTRAINT "FK_c55c70aebb84dc08bc16d962348"`);
        await queryRunner.query(`ALTER TABLE "api_keys" DROP CONSTRAINT "FK_a283bdef18876e525aefaec042f"`);
        await queryRunner.query(`ALTER TABLE "hts_test_results" DROP CONSTRAINT "FK_922e021c9a1380e147b3bf630bc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b23c65e50a758245a33ee35fda"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_87b8888186ca9769c960e92687"`);
        await queryRunner.query(`DROP TABLE "user_roles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_02ede4aec416291e538673b343"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_af582ae2b7d0d2df8d5637db89"`);
        await queryRunner.query(`DROP TABLE "api_usage_summaries"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5cee2ae4c3aacd99c17d1cebbb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_70767197fa888fa7aa8930e7ed"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d7c0e0f0cd7fe8916d7ef6f10f"`);
        await queryRunner.query(`DROP TABLE "api_usage_metrics"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_21a659804ed7bf61eb91688dea"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_648e3f5447f725579d7d4ffdfb"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_38baa0d834f93345a053c8202d"`);
        await queryRunner.query(`DROP TABLE "auto_topup_configs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9ea1509175fa294fc64d43a9fe"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3a2d09d943f39912a01831a927"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6ccf973355b70645eff37774de"`);
        await queryRunner.query(`DROP TABLE "subscriptions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b5e3ce8c220cbbebf5272c3bfa"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0ddf8494c8665a57c670287ccd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ac0f09364e3701d9ed35435288"`);
        await queryRunner.query(`DROP TABLE "invoices"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2c5b34b1029a5ec187a07e3f1f"`);
        await queryRunner.query(`DROP TABLE "credit_balances"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_932e7ec556c8c0af3333c8f7b0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ba3b1054ab30afce50760e8838"`);
        await queryRunner.query(`DROP TABLE "credit_purchases"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b6dacd2c81f576322e792bb526"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4733c4313650f4e34a8396599e"`);
        await queryRunner.query(`DROP TABLE "usage_records"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dd508eaabff6c38a0f25967918"`);
        await queryRunner.query(`DROP TABLE "calculation_scenarios"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9dcab0dbf595191c4724988b56"`);
        await queryRunner.query(`DROP TABLE "trade_agreement_eligibility"`);
        await queryRunner.query(`DROP TABLE "trade_agreements"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cbd8a4118ed5618028c7f69a00"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b6aae189e315d97a6fbd5a6f38"`);
        await queryRunner.query(`DROP TABLE "connectors"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_813ba8b85c38d2243b5b71c772"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7e502e476a12b2abab2b0f7269"`);
        await queryRunner.query(`DROP TABLE "connector_sync_logs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f03cb632d6211fa6d5d41793bb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_38a3037d2dcc8bd09c78e7a521"`);
        await queryRunner.query(`DROP TABLE "data_completeness_checks"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0032aa6713d64c5601ae5412b1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3b6aa9ca07be1b4f53b75bf467"`);
        await queryRunner.query(`DROP TABLE "export_jobs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_33678998322f0747aea098a47e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c72ab72ad43c72543ea3e1dc99"`);
        await queryRunner.query(`DROP TABLE "export_templates"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_523a3edcea18b308ceb8b671b9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3ddddeaec6465c669dcc32aba2"`);
        await queryRunner.query(`DROP TABLE "extension_feedback"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5f078e0aa6aa2980047d888b9e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7e2940ff5584fb7dea4555230d"`);
        await queryRunner.query(`DROP TABLE "scraping_metadata"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a9ccb235cd22d6ebc1d8d767c4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3599f6a5eef7b7c6fc480caf53"`);
        await queryRunner.query(`DROP TABLE "vision_analysis"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_03f8a5d7a29c1625820ca6cde0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9ca809344746f624026e2f2eae"`);
        await queryRunner.query(`DROP TABLE "country_configs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7072b9dacca5fe1d013cb557da"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_017e79432a698f47e2f3973e03"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_25b8340ab939226a9fa05e4391"`);
        await queryRunner.query(`DROP TABLE "hts_note_references"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_14c0130b2ae624ad184bd8aeed"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d4d58354c01ae6a638b01681fe"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a39683035c39b5c81a27d5ce89"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7519b107f3c5d023a64277b027"`);
        await queryRunner.query(`DROP TABLE "hts_notes"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f34b1b63eeea17b105b4c273f4"`);
        await queryRunner.query(`DROP TABLE "hts_note_rates"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_60887cda9cf0c783225f0040ce"`);
        await queryRunner.query(`DROP TABLE "hts_note_embeddings"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2089ee83745a2f45c4f97faf2a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a89c759be5f9fcd1afd18906c0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bdb0c523efff746aa871147aae"`);
        await queryRunner.query(`DROP TABLE "knowledge_chunks"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1145d957e031494b94e68021ce"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7a8dc27c3c19f76bff6be0ecc6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1a77c375eaf4080467b356057c"`);
        await queryRunner.query(`DROP TABLE "hts_documents"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9c15784c5886c071dd2b0bb39c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f702048eadb1548713d5cfa620"`);
        await queryRunner.query(`DROP TABLE "lookup_conversation_feedback"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_af45606581262d2382516b0c55"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e6ce664b504a300f1760ae7eb7"`);
        await queryRunner.query(`DROP TABLE "api_usage"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8fe2362cd9682152015795abfb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bd5e4db5ee0a20d404f0ecd2ff"`);
        await queryRunner.query(`DROP TABLE "lookup_conversation_messages"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8650a9ef31234b8d2d7d708f99"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_66e33a0c2623e71aed96aa6409"`);
        await queryRunner.query(`DROP TABLE "lookup_conversation_sessions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f8d088f75ecdc169397b949275"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5bdcebcb22a82f7a9647acc98d"`);
        await queryRunner.query(`DROP TABLE "product_classifications"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4ec25329691c172d07022d2ae2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_24f158c08586f16fc114147688"`);
        await queryRunner.query(`DROP TABLE "onboarding_progress"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8dc0371ea3f890340dd0ed248c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6b6cd716bfedee40ea98a1bae6"`);
        await queryRunner.query(`DROP TABLE "onboarding_templates"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_62360f6359a70e5fbca6b89e39"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5f466cf71c3b799322585b2eec"`);
        await queryRunner.query(`DROP TABLE "widget_sessions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_add42b564628399d7796abc4c8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_de85aab71cd538c95c408bd395"`);
        await queryRunner.query(`DROP TABLE "widget_configs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_57384430aa1959f4578046c9b8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0c81d2fda86d67e3b63d9743f2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_323a31abf1de12c7bb2d74412c"`);
        await queryRunner.query(`DROP TABLE "api_keys"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9b7ca6d30b94fef571cff87688"`);
        await queryRunner.query(`DROP TABLE "organizations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2d1b868dd95af635845525ce87"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_274df14b2a2b00d760f6560cb1"`);
        await queryRunner.query(`DROP TABLE "calculation_history"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ext_provider_formula_lookup"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ext_provider_formula_context"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ext_provider_formula_review_status"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_ext_provider_formula_latest_context"`);
        await queryRunner.query(`DROP TABLE "external_provider_formulas"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9fb329c9c48a32c253835b8b00"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_828743e7b996d8d013283f4647"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_50c08ba4ea3023ad32b23b75e2"`);
        await queryRunner.query(`DROP TABLE "hts_extra_taxes"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d6dea3fbb3cc33e44794956869"`);
        await queryRunner.query(`DROP TABLE "hts_formula_updates"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_52b4f0d506c903cc197ae4a2e5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f1c5c43dd3b79e649eca2e28db"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5e11c07c6ead521d6eeb5ff6eb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b9e53ef66cb5d5821cecbe5d95"`);
        await queryRunner.query(`DROP TABLE "hts_formula_candidates"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2a8c844d6b4da3adcc4befa189"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ba1499ab3c7580e44147eb51da"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_47dc86f5c1ec1a2419c9bdbc14"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_07981ba7d94d264616abca9503"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cc7a59dd162756f80ea7c7ae49"`);
        await queryRunner.query(`DROP TABLE "hts_import_history"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_835ebef092e3c4722a9a80a07e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_467d5a0909fa689f6b3a0929b6"`);
        await queryRunner.query(`DROP TABLE "hts_settings"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_909e9e12dd8aa8c55c09608023"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f4c3186cbda8e030ddf01c860f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7cde7d4f3e1e95df868ca77156"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_177a9dd2052799f50f21a72220"`);
        await queryRunner.query(`DROP TABLE "hts_stage_entries"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ccf0e1294afcdd5b332480e27f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_777a40f97b08644429f8dded77"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1e427d2642b67ffc3ef6274777"`);
        await queryRunner.query(`DROP TABLE "hts_stage_diffs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e7f8923bbaff00fe72b7790c5e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d4bcb0fc143114515226a6cfe9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0ddc2ac4f7d7553c676ad9f34b"`);
        await queryRunner.query(`DROP TABLE "hts_stage_validation_issues"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_193ed61ce278cad811a8637181"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_77e8583093c7d49009649ad59d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_77df6794987c59f9cfb2c92a17"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6ab6b2a85a4295d89281347557"`);
        await queryRunner.query(`DROP TABLE "hts_tariff_history_2025"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_922e021c9a1380e147b3bf630b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a5b7bd9b3bdd2e056725f462cd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_06f569d0b85f6a5c11b3803f1f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_03f262367d3b764de47770c7b4"`);
        await queryRunner.query(`DROP TABLE "hts_test_results"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_01f246f0fd1ebca76678d8da28"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8acd8cceae47d9f71dbcba824c"`);
        await queryRunner.query(`DROP TABLE "hts_test_cases"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_93e6f2a2f936e142ed01b07741"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_59a4b0d8d9345238fc99691ad2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0ba756d3d3513bbf0516126396"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f275d908c01a4093ac441a51ef"`);
        await queryRunner.query(`DROP TABLE "hts"`);
    }

}
