import { MigrationInterface, QueryRunner } from "typeorm";

export class FxRecordsAndAudit1779769311581 implements MigrationInterface {
    name = 'FxRecordsAndAudit1779769311581'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "marketplace_quotes" DROP CONSTRAINT "FK_mq_request"`);
        await queryRunner.query(`ALTER TABLE "marketplace_messages" DROP CONSTRAINT "FK_mm_conversation"`);
        await queryRunner.query(`ALTER TABLE "marketplace_conversations" DROP CONSTRAINT "FK_mc_request"`);
        await queryRunner.query(`ALTER TABLE "marketplace_broker_matches" DROP CONSTRAINT "FK_mbm_request"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_mr_request"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_mr_profile"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_mr_reviewer"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_mr_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_mr_rating"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bps_profile"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bps_org"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bps_date"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bps_profile_date"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bcl_org"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bcl_event"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bcl_created"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_mr_priority"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bcb_org"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_mm_conv_hidden"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bse_broker"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bse_business"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bse_rel"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bse_entry"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bse_type"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bse_created"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bmit_broker"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bmit_business"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bmit_rel"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bmit_entry"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bmit_line"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bmit_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bmit_due"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_br_scope"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_br_enabled"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_br_org"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bvr_org"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bvr_entry"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bvr_line"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bvr_rule"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bvr_sev"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bvr_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bvr_entry_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bpec_org"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bpec_entry"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bpec_type"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bpec_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bpec_due"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bpec_assignee"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bap_org"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bap_entry"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bap_created"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bd_org"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bd_target"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bd_suggestion"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bd_user"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bd_at"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bd_decision"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bai_org"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bai_target"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bai_type"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bai_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bai_created"`);
        await queryRunner.query(`DROP INDEX "public"."UX_broker_clients_broker_business"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bsm_org"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bsm_entry"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bsm_source"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bsm_type"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bsm_created"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bej_org"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bej_entry"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bej_adapter"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bej_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bej_created"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ba_org"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ba_type"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ba_status"`);
        await queryRunner.query(`CREATE TABLE "fx_records" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "quote_id" character varying(100) NOT NULL, "from_currency" character varying(3) NOT NULL, "to_currency" character varying(3) NOT NULL, "rate" numeric(18,8) NOT NULL, "provider" character varying(50) NOT NULL DEFAULT 'unknown', "observed_at" character varying(32) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c056e2cf7f1f5ff99350a1890ae" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2e25cfc2937109311ddba44f91" ON "fx_records" ("quote_id", "observed_at") `);
        await queryRunner.query(`ALTER TABLE "calculation_history" ADD "audit" jsonb`);
        await queryRunner.query(`ALTER TABLE "broker_rules" DROP CONSTRAINT "UQ_broker_rules_code"`);
        await queryRunner.query(`CREATE INDEX "IDX_1079da895626bff85bcebb6e37" ON "marketplace_reviews" ("rating") `);
        await queryRunner.query(`CREATE INDEX "IDX_0e49a499e05edf992142a6f2b5" ON "marketplace_reviews" ("moderation_status") `);
        await queryRunner.query(`CREATE INDEX "IDX_f606bd818d7e4f7f1f2f92c02e" ON "marketplace_reviews" ("reviewer_organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_1b07b8d76bc57b2d07dee9b841" ON "marketplace_reviews" ("broker_profile_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_c1a71a639d1a4d75e30b2080ac" ON "marketplace_reviews" ("request_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_dd234318053c95804c9d63f450" ON "broker_performance_snapshots" ("broker_profile_id", "snapshot_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_fc2466427e1a9201d1dacd2238" ON "broker_performance_snapshots" ("snapshot_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_8ec2014af10682bf4d4104a32b" ON "broker_performance_snapshots" ("broker_organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f00dd724421e4e3726581e34b7" ON "broker_performance_snapshots" ("broker_profile_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_0bc072b599d6b53478f4d9745e" ON "broker_credit_ledger" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_d56279885135b6effcc472024b" ON "broker_credit_ledger" ("event_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_06d0d878de48d947e77af6ebfc" ON "broker_credit_ledger" ("organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_2ec7f8efe4a31384567e388822" ON "marketplace_requests" ("priority") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_75f91b77b908121828b1c128a3" ON "broker_credit_balances" ("organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_692a9b155b5f1b1ead80c213e1" ON "marketplace_messages" ("conversation_id", "hidden") `);
        await queryRunner.query(`CREATE INDEX "IDX_0572a4202f22633a4e0dcae6b2" ON "broker_status_events" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_e8386fed256ae23a5074021dbb" ON "broker_status_events" ("event_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_7e82022964878a25db39dc837a" ON "broker_status_events" ("entry_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f70041f3f8906be4b09fcc93ef" ON "broker_status_events" ("relationship_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ab5030532716e5b5211223be70" ON "broker_status_events" ("business_organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_59846673151eeedce028c1d812" ON "broker_status_events" ("broker_organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_983c5218d917f219422e97cbe8" ON "broker_missing_info_tasks" ("due_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_0d024e47b0400e89ff062b9cfa" ON "broker_missing_info_tasks" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_bef1c56a18e31c0eed6777c8c6" ON "broker_missing_info_tasks" ("line_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_8c808eb14aedd38ff52df2c7d0" ON "broker_missing_info_tasks" ("entry_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9e923e141a89c39b9c05a0c981" ON "broker_missing_info_tasks" ("relationship_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_2f058a612df48a84123e77a796" ON "broker_missing_info_tasks" ("business_organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_313b218b3d2538c30ecc6c1b84" ON "broker_missing_info_tasks" ("broker_organization_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_9b14623a51c31b4ee8fd68dea4" ON "broker_rules" ("code") `);
        await queryRunner.query(`CREATE INDEX "IDX_870d581b82f5d11c90b7ee4d46" ON "broker_rules" ("organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_8e3045b728a1cf1a334830feec" ON "broker_rules" ("enabled") `);
        await queryRunner.query(`CREATE INDEX "IDX_58a3a4897c8b315ddee89d97c1" ON "broker_rules" ("scope") `);
        await queryRunner.query(`CREATE INDEX "IDX_b724c6c404d4efe4179e4c83b1" ON "broker_validation_results" ("entry_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_ae486f3a4883e4c5866fd6b75b" ON "broker_validation_results" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_44a5a08ecb2abb8de8db2814fe" ON "broker_validation_results" ("severity") `);
        await queryRunner.query(`CREATE INDEX "IDX_7f164a69469b0bb57f80186d29" ON "broker_validation_results" ("rule_code") `);
        await queryRunner.query(`CREATE INDEX "IDX_884c1f287fec28b051a7bd6f00" ON "broker_validation_results" ("line_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f58211a362cc7a7e885ba31b8d" ON "broker_validation_results" ("entry_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_3fc1299122e7f2831467863111" ON "broker_validation_results" ("broker_organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f91939e7a739099d9cbb6f87b2" ON "broker_post_entry_cases" ("assignee_user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_59b08e78e41aefe824eb6d4b1d" ON "broker_post_entry_cases" ("due_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_f836712da070885550e2591b9e" ON "broker_post_entry_cases" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_13b244dc8a5628ecf8f6004128" ON "broker_post_entry_cases" ("case_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_6ed93a9b6ddaee679d8c6a9a45" ON "broker_post_entry_cases" ("entry_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_fcef72dfd2a8533e288a6e9b75" ON "broker_post_entry_cases" ("broker_organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_8aab37c3911c1d19d58828e78c" ON "broker_audit_packs" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_72684641344b93005548d5dc3d" ON "broker_audit_packs" ("entry_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a9c7547a5c59bdee998e7fbabc" ON "broker_audit_packs" ("broker_organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_838b1ace53786bff17de63716a" ON "broker_decisions" ("decision") `);
        await queryRunner.query(`CREATE INDEX "IDX_575c75672c107b04a7e153cc7d" ON "broker_decisions" ("decided_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_a256b841227b718030432fd415" ON "broker_decisions" ("decided_by_user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_1642a0fbd1716193fcfc1950ec" ON "broker_decisions" ("suggestion_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_7c8562fa0d44679dd0a114ab5e" ON "broker_decisions" ("target_type", "target_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d965c353cb19b35656c8270932" ON "broker_decisions" ("broker_organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c5a7afc7a74a8eb14ba0c2892b" ON "broker_ai_suggestions" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_b29ca0b5247b69414e757faaf7" ON "broker_ai_suggestions" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_0cbd0ebbdad67533d605dcff58" ON "broker_ai_suggestions" ("suggestion_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_eec889fff078818cbd1705901c" ON "broker_ai_suggestions" ("target_type", "target_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_805511fd9e60209d33718c40bf" ON "broker_ai_suggestions" ("broker_organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_0c5bcfcee634619fc3a278ec16" ON "broker_status_messages" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_ad44b41f84bb65be52f1431219" ON "broker_status_messages" ("message_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_4726642e1b73dda45ea6ad7d36" ON "broker_status_messages" ("source") `);
        await queryRunner.query(`CREATE INDEX "IDX_0ef1e6e260d8d506edb8641f4d" ON "broker_status_messages" ("entry_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_8347ba73b1e2cace7fd8690de4" ON "broker_status_messages" ("organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_421c272ea2ee715c46d0f2e528" ON "broker_export_jobs" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_f03bc0cfef7d06e61af84a6fc3" ON "broker_export_jobs" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_8d4fad7d56883ec9fab74edb5f" ON "broker_export_jobs" ("adapter_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d66aa9d8e62395d63550a4ce46" ON "broker_export_jobs" ("entry_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_586f30b278ca4f20123ba08838" ON "broker_export_jobs" ("organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_334e288c051226a6213b6e3679" ON "broker_adapters" ("organization_id", "adapter_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_8bf84d3c0a9cce20f185f77080" ON "broker_adapters" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_015e05a00879715e5a86c35cc5" ON "broker_adapters" ("adapter_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_a1da31e2439ed5766b20389a1a" ON "broker_adapters" ("organization_id") `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "public"."IDX_a1da31e2439ed5766b20389a1a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_015e05a00879715e5a86c35cc5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8bf84d3c0a9cce20f185f77080"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_334e288c051226a6213b6e3679"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_586f30b278ca4f20123ba08838"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d66aa9d8e62395d63550a4ce46"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8d4fad7d56883ec9fab74edb5f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f03bc0cfef7d06e61af84a6fc3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_421c272ea2ee715c46d0f2e528"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8347ba73b1e2cace7fd8690de4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0ef1e6e260d8d506edb8641f4d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4726642e1b73dda45ea6ad7d36"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ad44b41f84bb65be52f1431219"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0c5bcfcee634619fc3a278ec16"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_805511fd9e60209d33718c40bf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eec889fff078818cbd1705901c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0cbd0ebbdad67533d605dcff58"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b29ca0b5247b69414e757faaf7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c5a7afc7a74a8eb14ba0c2892b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d965c353cb19b35656c8270932"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7c8562fa0d44679dd0a114ab5e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1642a0fbd1716193fcfc1950ec"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a256b841227b718030432fd415"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_575c75672c107b04a7e153cc7d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_838b1ace53786bff17de63716a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a9c7547a5c59bdee998e7fbabc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_72684641344b93005548d5dc3d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8aab37c3911c1d19d58828e78c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fcef72dfd2a8533e288a6e9b75"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6ed93a9b6ddaee679d8c6a9a45"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_13b244dc8a5628ecf8f6004128"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f836712da070885550e2591b9e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_59b08e78e41aefe824eb6d4b1d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f91939e7a739099d9cbb6f87b2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3fc1299122e7f2831467863111"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f58211a362cc7a7e885ba31b8d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_884c1f287fec28b051a7bd6f00"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7f164a69469b0bb57f80186d29"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_44a5a08ecb2abb8de8db2814fe"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ae486f3a4883e4c5866fd6b75b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b724c6c404d4efe4179e4c83b1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_58a3a4897c8b315ddee89d97c1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8e3045b728a1cf1a334830feec"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_870d581b82f5d11c90b7ee4d46"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9b14623a51c31b4ee8fd68dea4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_313b218b3d2538c30ecc6c1b84"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2f058a612df48a84123e77a796"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9e923e141a89c39b9c05a0c981"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8c808eb14aedd38ff52df2c7d0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bef1c56a18e31c0eed6777c8c6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0d024e47b0400e89ff062b9cfa"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_983c5218d917f219422e97cbe8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_59846673151eeedce028c1d812"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ab5030532716e5b5211223be70"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f70041f3f8906be4b09fcc93ef"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7e82022964878a25db39dc837a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e8386fed256ae23a5074021dbb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0572a4202f22633a4e0dcae6b2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_692a9b155b5f1b1ead80c213e1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_75f91b77b908121828b1c128a3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2ec7f8efe4a31384567e388822"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_06d0d878de48d947e77af6ebfc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d56279885135b6effcc472024b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0bc072b599d6b53478f4d9745e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f00dd724421e4e3726581e34b7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8ec2014af10682bf4d4104a32b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fc2466427e1a9201d1dacd2238"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dd234318053c95804c9d63f450"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c1a71a639d1a4d75e30b2080ac"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1b07b8d76bc57b2d07dee9b841"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f606bd818d7e4f7f1f2f92c02e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0e49a499e05edf992142a6f2b5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1079da895626bff85bcebb6e37"`);
        await queryRunner.query(`ALTER TABLE "broker_rules" ADD CONSTRAINT "UQ_broker_rules_code" UNIQUE ("code")`);
        await queryRunner.query(`ALTER TABLE "calculation_history" DROP COLUMN "audit"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2e25cfc2937109311ddba44f91"`);
        await queryRunner.query(`DROP TABLE "fx_records"`);
        await queryRunner.query(`CREATE INDEX "IDX_ba_status" ON "broker_adapters" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_ba_type" ON "broker_adapters" ("adapter_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_ba_org" ON "broker_adapters" ("organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_bej_created" ON "broker_export_jobs" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_bej_status" ON "broker_export_jobs" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_bej_adapter" ON "broker_export_jobs" ("adapter_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_bej_entry" ON "broker_export_jobs" ("entry_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_bej_org" ON "broker_export_jobs" ("organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_bsm_created" ON "broker_status_messages" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_bsm_type" ON "broker_status_messages" ("message_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_bsm_source" ON "broker_status_messages" ("source") `);
        await queryRunner.query(`CREATE INDEX "IDX_bsm_entry" ON "broker_status_messages" ("entry_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_bsm_org" ON "broker_status_messages" ("organization_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UX_broker_clients_broker_business" ON "broker_clients" ("broker_organization_id", "client_organization_id") WHERE (client_organization_id IS NOT NULL)`);
        await queryRunner.query(`CREATE INDEX "IDX_bai_created" ON "broker_ai_suggestions" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_bai_status" ON "broker_ai_suggestions" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_bai_type" ON "broker_ai_suggestions" ("suggestion_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_bai_target" ON "broker_ai_suggestions" ("target_id", "target_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_bai_org" ON "broker_ai_suggestions" ("broker_organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_bd_decision" ON "broker_decisions" ("decision") `);
        await queryRunner.query(`CREATE INDEX "IDX_bd_at" ON "broker_decisions" ("decided_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_bd_user" ON "broker_decisions" ("decided_by_user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_bd_suggestion" ON "broker_decisions" ("suggestion_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_bd_target" ON "broker_decisions" ("target_id", "target_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_bd_org" ON "broker_decisions" ("broker_organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_bap_created" ON "broker_audit_packs" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_bap_entry" ON "broker_audit_packs" ("entry_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_bap_org" ON "broker_audit_packs" ("broker_organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_bpec_assignee" ON "broker_post_entry_cases" ("assignee_user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_bpec_due" ON "broker_post_entry_cases" ("due_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_bpec_status" ON "broker_post_entry_cases" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_bpec_type" ON "broker_post_entry_cases" ("case_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_bpec_entry" ON "broker_post_entry_cases" ("entry_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_bpec_org" ON "broker_post_entry_cases" ("broker_organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_bvr_entry_status" ON "broker_validation_results" ("entry_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_bvr_status" ON "broker_validation_results" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_bvr_sev" ON "broker_validation_results" ("severity") `);
        await queryRunner.query(`CREATE INDEX "IDX_bvr_rule" ON "broker_validation_results" ("rule_code") `);
        await queryRunner.query(`CREATE INDEX "IDX_bvr_line" ON "broker_validation_results" ("line_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_bvr_entry" ON "broker_validation_results" ("entry_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_bvr_org" ON "broker_validation_results" ("broker_organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_br_org" ON "broker_rules" ("organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_br_enabled" ON "broker_rules" ("enabled") `);
        await queryRunner.query(`CREATE INDEX "IDX_br_scope" ON "broker_rules" ("scope") `);
        await queryRunner.query(`CREATE INDEX "IDX_bmit_due" ON "broker_missing_info_tasks" ("due_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_bmit_status" ON "broker_missing_info_tasks" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_bmit_line" ON "broker_missing_info_tasks" ("line_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_bmit_entry" ON "broker_missing_info_tasks" ("entry_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_bmit_rel" ON "broker_missing_info_tasks" ("relationship_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_bmit_business" ON "broker_missing_info_tasks" ("business_organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_bmit_broker" ON "broker_missing_info_tasks" ("broker_organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_bse_created" ON "broker_status_events" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_bse_type" ON "broker_status_events" ("event_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_bse_entry" ON "broker_status_events" ("entry_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_bse_rel" ON "broker_status_events" ("relationship_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_bse_business" ON "broker_status_events" ("business_organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_bse_broker" ON "broker_status_events" ("broker_organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_mm_conv_hidden" ON "marketplace_messages" ("conversation_id", "hidden") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_bcb_org" ON "broker_credit_balances" ("organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_mr_priority" ON "marketplace_requests" ("priority") `);
        await queryRunner.query(`CREATE INDEX "IDX_bcl_created" ON "broker_credit_ledger" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_bcl_event" ON "broker_credit_ledger" ("event_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_bcl_org" ON "broker_credit_ledger" ("organization_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_bps_profile_date" ON "broker_performance_snapshots" ("broker_profile_id", "snapshot_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_bps_date" ON "broker_performance_snapshots" ("snapshot_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_bps_org" ON "broker_performance_snapshots" ("broker_organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_bps_profile" ON "broker_performance_snapshots" ("broker_profile_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_mr_rating" ON "marketplace_reviews" ("rating") `);
        await queryRunner.query(`CREATE INDEX "IDX_mr_status" ON "marketplace_reviews" ("moderation_status") `);
        await queryRunner.query(`CREATE INDEX "IDX_mr_reviewer" ON "marketplace_reviews" ("reviewer_organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_mr_profile" ON "marketplace_reviews" ("broker_profile_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_mr_request" ON "marketplace_reviews" ("request_id") `);
        await queryRunner.query(`ALTER TABLE "marketplace_broker_matches" ADD CONSTRAINT "FK_mbm_request" FOREIGN KEY ("request_id") REFERENCES "marketplace_requests"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "marketplace_conversations" ADD CONSTRAINT "FK_mc_request" FOREIGN KEY ("request_id") REFERENCES "marketplace_requests"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "marketplace_messages" ADD CONSTRAINT "FK_mm_conversation" FOREIGN KEY ("conversation_id") REFERENCES "marketplace_conversations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "marketplace_quotes" ADD CONSTRAINT "FK_mq_request" FOREIGN KEY ("request_id") REFERENCES "marketplace_requests"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
