import { MigrationInterface, QueryRunner } from "typeorm";

export class Digitrend1779573500537 implements MigrationInterface {
    name = 'Digitrend1779573500537'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "public"."IDX_lookup_classification_job_org_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_lookup_classification_job_created_by_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_lookup_classification_job_status_created_at"`);
        await queryRunner.query(`CREATE TABLE "landed_cost_quotes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "api_key_id" uuid, "idempotency_key" character varying(128), "status" character varying(24) NOT NULL DEFAULT 'calculated', "request_json" jsonb NOT NULL, "response_json" jsonb NOT NULL, "hts_snapshot_ids" jsonb, "tax_rule_snapshot_ids" jsonb, "fee_rule_snapshot_ids" jsonb, "low_value_rule_snapshot_ids" jsonb, "exchange_rate_snapshot_id" uuid, "formula_ids" jsonb, "confidence" numeric(3,2), "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "totals" jsonb, "confirmed_at" TIMESTAMP WITH TIME ZONE, "request_fingerprint" character varying(128), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7f8e7a8f0673d9e8f8c14ed5dc0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6f35ce714131823b8f5dc4da1c" ON "landed_cost_quotes" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_88f62daaf2cb36efae5e3d6a3d" ON "landed_cost_quotes" ("expires_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_9ad7c82df42359104bfc59c2f6" ON "landed_cost_quotes" ("organization_id", "status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_03ebc04d9f965a57f000df9dc4" ON "landed_cost_quotes" ("organization_id", "idempotency_key") `);
        await queryRunner.query(`CREATE TABLE "landed_cost_lines" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "quote_id" uuid NOT NULL, "line_number" integer NOT NULL, "sku" character varying(128), "hs_code" character varying(20), "destination_code" character varying(20), "country_of_origin" character varying(8) NOT NULL, "declared_value" numeric(12,4) NOT NULL, "weight_kg" numeric(12,4), "quantity" integer, "base_duty" numeric(12,4) NOT NULL DEFAULT '0', "additional_tariffs" numeric(12,4) NOT NULL DEFAULT '0', "fees" numeric(12,4) NOT NULL DEFAULT '0', "taxes" numeric(12,4) NOT NULL DEFAULT '0', "total_duty" numeric(12,4) NOT NULL DEFAULT '0', "landed_cost" numeric(12,4) NOT NULL DEFAULT '0', "duty_breakdown" jsonb, "tax_breakdown" jsonb, "fee_breakdown" jsonb, "controls" jsonb, "warnings" jsonb, "source_citations" jsonb, "classification_source" character varying(16) NOT NULL DEFAULT 'provided', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0bf492d8893681b25ad7d79d4e3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_428c97a7563ee938fd7873b45b" ON "landed_cost_lines" ("quote_id", "line_number") `);
        await queryRunner.query(`CREATE INDEX "IDX_e150f1d0fedfad74f634c9cf95" ON "landed_cost_lines" ("quote_id") `);
        await queryRunner.query(`CREATE TABLE "exchange_rate_snapshots" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "effective_date" date NOT NULL, "source" character varying(32) NOT NULL DEFAULT 'ecb', "rates" jsonb NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_601f5fd2bf32a8388dbe8629dcc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e3995b46c7e0521925604b6880" ON "exchange_rate_snapshots" ("effective_date", "source") `);
        await queryRunner.query(`CREATE INDEX "IDX_533390bc44f4ed52637ef14a1a" ON "exchange_rate_snapshots" ("effective_date") `);
        await queryRunner.query(`CREATE TABLE "tariff_sources" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "jurisdiction_code" character varying(8) NOT NULL, "source_name" character varying(128) NOT NULL, "source_url" text NOT NULL, "license" character varying(64), "retrieval_method" character varying(32) NOT NULL, "update_cadence" character varying(24) NOT NULL, "parser_type" character varying(32) NOT NULL, "latest_version" character varying(64), "latest_import_at" TIMESTAMP WITH TIME ZONE, "is_active" boolean NOT NULL DEFAULT true, "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d5bb686137361a38a34cb2e53e8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_8b47558523bc15ac31916f72e4" ON "tariff_sources" ("jurisdiction_code", "source_name") `);
        await queryRunner.query(`CREATE INDEX "IDX_87d8408b44183018e04e7fad85" ON "tariff_sources" ("jurisdiction_code") `);
        await queryRunner.query(`CREATE TABLE "tax_rules" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "jurisdiction_code" character varying(8) NOT NULL, "member_state_code" character varying(8), "tax_type" character varying(32) NOT NULL, "name" character varying(128) NOT NULL, "rate" numeric(6,4) NOT NULL, "base_formula" text, "collection_point" character varying(24) NOT NULL, "threshold_id" uuid, "exemptions" jsonb, "applies_when" jsonb, "effective_from" date NOT NULL, "effective_to" date, "source_citation_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_29b500604ee0ac9e162de1bfa6d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2999eb13647d2d66c49d0a2610" ON "tax_rules" ("effective_from") `);
        await queryRunner.query(`CREATE INDEX "IDX_5b89bb960a207e2993b6e56607" ON "tax_rules" ("jurisdiction_code", "member_state_code", "tax_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_902fb79bef312b19eea68e9c72" ON "tax_rules" ("jurisdiction_code") `);
        await queryRunner.query(`CREATE TABLE "tariff_snapshots" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "source_id" uuid NOT NULL, "version" character varying(64) NOT NULL, "effective_date" date NOT NULL, "downloaded_at" TIMESTAMP WITH TIME ZONE NOT NULL, "checksum" character varying(128) NOT NULL, "storage_uri" text, "import_job_id" uuid, "release_url" text, "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1edd99e43a92064cb4d84f659c2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f7b72803ce38d348f996aa41de" ON "tariff_snapshots" ("effective_date") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d5c33f1e06980127c0d44b7f2e" ON "tariff_snapshots" ("source_id", "version") `);
        await queryRunner.query(`CREATE INDEX "IDX_790ef4bcffdaf1282fcfdbf8dd" ON "tariff_snapshots" ("source_id") `);
        await queryRunner.query(`CREATE TABLE "low_value_rules" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "jurisdiction_code" character varying(8) NOT NULL, "currency" character varying(8) NOT NULL, "threshold" numeric(15,4) NOT NULL, "duty_treatment" character varying(32) NOT NULL, "tax_treatment" character varying(32) NOT NULL, "seller_collection" boolean NOT NULL DEFAULT false, "excluded_hs_prefixes" jsonb, "effective_from" date NOT NULL, "effective_to" date, "source_citation_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_43f131b0b68047f1f486ac668b0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f8ee26f35434b3ab44039f6455" ON "low_value_rules" ("jurisdiction_code") `);
        await queryRunner.query(`CREATE INDEX "IDX_1aa4a381b7f2061e5ee0e78586" ON "low_value_rules" ("jurisdiction_code", "effective_from") `);
        await queryRunner.query(`CREATE TABLE "source_citations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "snapshot_id" uuid, "entity_type" character varying(64) NOT NULL, "entity_id" character varying(128) NOT NULL, "row_identifier" character varying(255), "excerpt" text, "page_ref" character varying(64), "effective_date" date, "confidence" numeric(3,2), "parser_version" character varying(64), "parser_method" character varying(64), "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_958d65fe4e0cb0771fffa45265b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a76aad4a667935986d506c380f" ON "source_citations" ("entity_type", "entity_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f02f601eabae11a5ecfd259431" ON "source_citations" ("snapshot_id") `);
        await queryRunner.query(`CREATE TABLE "jurisdictions" ("code" character varying(8) NOT NULL, "display_name" character varying(255) NOT NULL, "type" character varying(24) NOT NULL, "parent_code" character varying(8), "currency_code" character varying(8) NOT NULL, "default_locale" character varying(16), "tariff_schema" character varying(32) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e33b5f6afb84e58de0c2399edb0" PRIMARY KEY ("code"))`);
        await queryRunner.query(`CREATE INDEX "IDX_df847b3361d1459beaeedf6484" ON "jurisdictions" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_3bb3f3f9192d95db65371d574c" ON "jurisdictions" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_dce4853f6c10c0c405103de1f1" ON "jurisdictions" ("parent_code") `);
        await queryRunner.query(`CREATE TABLE "fee_rules" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "jurisdiction_code" character varying(8) NOT NULL, "fee_type" character varying(32) NOT NULL, "name" character varying(128) NOT NULL, "rate_type" character varying(24) NOT NULL, "formula" text NOT NULL, "min_amount" numeric(15,4), "max_amount" numeric(15,4), "transport_mode" character varying(16), "declaration_type" character varying(24), "threshold_amount" numeric(15,4), "applies_when" jsonb, "effective_from" date NOT NULL, "effective_to" date, "source_citation_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_10829781c2028cd90e62c6626c4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_fecf525f542eba846c0995e8a8" ON "fee_rules" ("effective_from") `);
        await queryRunner.query(`CREATE INDEX "IDX_5028883f0e65a84e7407b53e76" ON "fee_rules" ("jurisdiction_code", "fee_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_75747b3fe759491506821f4628" ON "fee_rules" ("jurisdiction_code") `);
        await queryRunner.query(`CREATE TABLE "jurisdiction_controls" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "jurisdiction_code" character varying(8) NOT NULL, "classification_code" character varying(20) NOT NULL, "control_type" character varying(24) NOT NULL, "severity" character varying(16) NOT NULL, "description" text, "source_citation_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_19fd701a1417dbf4a2aa7d88da4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b905200ff88f6464cc4ec45109" ON "jurisdiction_controls" ("control_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_26e5dd8d1e8b7a773d2d2f27da" ON "jurisdiction_controls" ("jurisdiction_code", "classification_code") `);
        await queryRunner.query(`CREATE INDEX "IDX_4267b9e6dea5490b8930f688a5" ON "jurisdiction_controls" ("jurisdiction_code") `);
        await queryRunner.query(`CREATE TABLE "catalog_products" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "external_id" character varying(128), "name" character varying(255) NOT NULL, "description" text, "category_path" character varying(255), "default_country_of_origin" character varying(8), "default_hs_code" character varying(20), "manufacturer_id" character varying(64), "gtin" character varying(32), "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9f7a978657257a0bb575a174f0a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d2dfedd75b26bfcf0d8e1dd252" ON "catalog_products" ("organization_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_df10fdb30f7103184438909162" ON "catalog_products" ("organization_id", "gtin") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_26c32204770631b13f69729aee" ON "catalog_products" ("organization_id", "external_id") `);
        await queryRunner.query(`CREATE TABLE "catalog_product_variants" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "product_id" uuid NOT NULL, "sku" character varying(128) NOT NULL, "attributes" jsonb, "weight_kg" numeric(15,4), "unit_value" numeric(15,4), "currency" character varying(8), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b7d4f38520eb43d6002d5988235" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_4e2a3461a7544bdabc04854fbb" ON "catalog_product_variants" ("product_id", "sku") `);
        await queryRunner.query(`CREATE INDEX "IDX_7779d27ec0bcb14150b92e34ad" ON "catalog_product_variants" ("product_id") `);
        await queryRunner.query(`CREATE TABLE "catalog_product_materials" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "product_id" uuid NOT NULL, "material" character varying(128) NOT NULL, "percent" numeric(5,2) NOT NULL, "verified_by" character varying(128), "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_eecc044fa8a35d98f5c72f5079a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b93d07b6d941a1a55258eeac8c" ON "catalog_product_materials" ("product_id") `);
        await queryRunner.query(`CREATE TABLE "catalog_product_images" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "product_id" uuid NOT NULL, "url" text NOT NULL, "role" character varying(16) NOT NULL DEFAULT 'primary', "added_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f678cb096cae1eead50afa4c814" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_965a4f6374eec16b7f809814ad" ON "catalog_product_images" ("product_id") `);
        await queryRunner.query(`CREATE TABLE "catalog_classifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "product_id" uuid NOT NULL, "destination_jurisdiction_code" character varying(8) NOT NULL, "hs6" character varying(6) NOT NULL, "destination_code" character varying(20) NOT NULL, "status" character varying(24) NOT NULL DEFAULT 'estimated', "confidence" numeric(3,2) NOT NULL, "confirmed_at" TIMESTAMP WITH TIME ZONE, "confirmed_by" character varying(128), "expires_at" TIMESTAMP WITH TIME ZONE, "source_citation_id" uuid, "model_version" character varying(64), "features_used" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_df16c6eed55d547e2d55dbc04f7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cf74ed8803e96faaaf5e972313" ON "catalog_classifications" ("expires_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_368464a8d654d9916439208b0c" ON "catalog_classifications" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_eea4b81d5f576c99f669693577" ON "catalog_classifications" ("product_id", "destination_jurisdiction_code") `);
        await queryRunner.query(`CREATE TABLE "catalog_classification_candidates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "product_id" uuid NOT NULL, "destination_jurisdiction_code" character varying(8) NOT NULL, "hs6" character varying(6) NOT NULL, "destination_code" character varying(20) NOT NULL, "confidence" numeric(3,2) NOT NULL, "rationale" text, "rank" integer NOT NULL, "produced_at" TIMESTAMP WITH TIME ZONE NOT NULL, "produced_by" character varying(64) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d2c2c573dc3359cea0888f49bec" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a26529779a16a1d497b5fbc689" ON "catalog_classification_candidates" ("produced_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_fd62633c156d4517d0ff26aecb" ON "catalog_classification_candidates" ("product_id", "destination_jurisdiction_code") `);
        await queryRunner.query(`CREATE INDEX "IDX_e5c60d395fd28a27515023e8f5" ON "catalog_classification_candidates" ("product_id") `);
        await queryRunner.query(`ALTER TABLE "hts" ADD "rate_text_hash" character varying(64)`);
        await queryRunner.query(`ALTER TABLE "hts" ADD "formula_confidence" numeric(3,2)`);
        await queryRunner.query(`ALTER TABLE "hts" ADD "formula_generated_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "hts" ADD "formula_source_citation_id" uuid`);
        await queryRunner.query(`ALTER TABLE "hts_formula_candidates" ADD "rate_text" text`);
        await queryRunner.query(`ALTER TABLE "hts_formula_candidates" ADD "footnote_ref" text`);
        await queryRunner.query(`ALTER TABLE "hts_formula_candidates" ADD "chapter99_ref" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "hts_formula_candidates" ADD "legal_note_ref" text`);
        await queryRunner.query(`ALTER TABLE "hts_formula_candidates" ADD "parser_method" character varying(40)`);
        await queryRunner.query(`ALTER TABLE "hts_formula_candidates" ADD "parser_version" character varying(40)`);
        await queryRunner.query(`ALTER TABLE "hts_formula_candidates" ADD "source_citation_id" uuid`);
        await queryRunner.query(`ALTER TABLE "hts_formula_candidates" ADD "superseded_by" uuid`);
        await queryRunner.query(`ALTER TABLE "shopify_sessions" ADD "calculate_duty" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "shopify_sessions" ADD "display_at_checkout" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`CREATE INDEX "IDX_868e0e5a8f316043c76a45f750" ON "lookup_classification_job" ("status", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_08563c9b6534b1c2adb77d39cb" ON "lookup_classification_job" ("created_by", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_8571e1029ba307804031ab4554" ON "lookup_classification_job" ("organization_id", "status") `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "public"."IDX_8571e1029ba307804031ab4554"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_08563c9b6534b1c2adb77d39cb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_868e0e5a8f316043c76a45f750"`);
        await queryRunner.query(`ALTER TABLE "shopify_sessions" DROP COLUMN "display_at_checkout"`);
        await queryRunner.query(`ALTER TABLE "shopify_sessions" DROP COLUMN "calculate_duty"`);
        await queryRunner.query(`ALTER TABLE "hts_formula_candidates" DROP COLUMN "superseded_by"`);
        await queryRunner.query(`ALTER TABLE "hts_formula_candidates" DROP COLUMN "source_citation_id"`);
        await queryRunner.query(`ALTER TABLE "hts_formula_candidates" DROP COLUMN "parser_version"`);
        await queryRunner.query(`ALTER TABLE "hts_formula_candidates" DROP COLUMN "parser_method"`);
        await queryRunner.query(`ALTER TABLE "hts_formula_candidates" DROP COLUMN "legal_note_ref"`);
        await queryRunner.query(`ALTER TABLE "hts_formula_candidates" DROP COLUMN "chapter99_ref"`);
        await queryRunner.query(`ALTER TABLE "hts_formula_candidates" DROP COLUMN "footnote_ref"`);
        await queryRunner.query(`ALTER TABLE "hts_formula_candidates" DROP COLUMN "rate_text"`);
        await queryRunner.query(`ALTER TABLE "hts" DROP COLUMN "formula_source_citation_id"`);
        await queryRunner.query(`ALTER TABLE "hts" DROP COLUMN "formula_generated_at"`);
        await queryRunner.query(`ALTER TABLE "hts" DROP COLUMN "formula_confidence"`);
        await queryRunner.query(`ALTER TABLE "hts" DROP COLUMN "rate_text_hash"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e5c60d395fd28a27515023e8f5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fd62633c156d4517d0ff26aecb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a26529779a16a1d497b5fbc689"`);
        await queryRunner.query(`DROP TABLE "catalog_classification_candidates"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eea4b81d5f576c99f669693577"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_368464a8d654d9916439208b0c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cf74ed8803e96faaaf5e972313"`);
        await queryRunner.query(`DROP TABLE "catalog_classifications"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_965a4f6374eec16b7f809814ad"`);
        await queryRunner.query(`DROP TABLE "catalog_product_images"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b93d07b6d941a1a55258eeac8c"`);
        await queryRunner.query(`DROP TABLE "catalog_product_materials"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7779d27ec0bcb14150b92e34ad"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4e2a3461a7544bdabc04854fbb"`);
        await queryRunner.query(`DROP TABLE "catalog_product_variants"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_26c32204770631b13f69729aee"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_df10fdb30f7103184438909162"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d2dfedd75b26bfcf0d8e1dd252"`);
        await queryRunner.query(`DROP TABLE "catalog_products"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4267b9e6dea5490b8930f688a5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_26e5dd8d1e8b7a773d2d2f27da"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b905200ff88f6464cc4ec45109"`);
        await queryRunner.query(`DROP TABLE "jurisdiction_controls"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_75747b3fe759491506821f4628"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5028883f0e65a84e7407b53e76"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fecf525f542eba846c0995e8a8"`);
        await queryRunner.query(`DROP TABLE "fee_rules"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dce4853f6c10c0c405103de1f1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3bb3f3f9192d95db65371d574c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_df847b3361d1459beaeedf6484"`);
        await queryRunner.query(`DROP TABLE "jurisdictions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f02f601eabae11a5ecfd259431"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a76aad4a667935986d506c380f"`);
        await queryRunner.query(`DROP TABLE "source_citations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1aa4a381b7f2061e5ee0e78586"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f8ee26f35434b3ab44039f6455"`);
        await queryRunner.query(`DROP TABLE "low_value_rules"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_790ef4bcffdaf1282fcfdbf8dd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d5c33f1e06980127c0d44b7f2e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f7b72803ce38d348f996aa41de"`);
        await queryRunner.query(`DROP TABLE "tariff_snapshots"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_902fb79bef312b19eea68e9c72"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5b89bb960a207e2993b6e56607"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2999eb13647d2d66c49d0a2610"`);
        await queryRunner.query(`DROP TABLE "tax_rules"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_87d8408b44183018e04e7fad85"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8b47558523bc15ac31916f72e4"`);
        await queryRunner.query(`DROP TABLE "tariff_sources"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_533390bc44f4ed52637ef14a1a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e3995b46c7e0521925604b6880"`);
        await queryRunner.query(`DROP TABLE "exchange_rate_snapshots"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e150f1d0fedfad74f634c9cf95"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_428c97a7563ee938fd7873b45b"`);
        await queryRunner.query(`DROP TABLE "landed_cost_lines"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_03ebc04d9f965a57f000df9dc4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9ad7c82df42359104bfc59c2f6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_88f62daaf2cb36efae5e3d6a3d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6f35ce714131823b8f5dc4da1c"`);
        await queryRunner.query(`DROP TABLE "landed_cost_quotes"`);
        await queryRunner.query(`CREATE INDEX "IDX_lookup_classification_job_status_created_at" ON "lookup_classification_job" ("created_at", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_lookup_classification_job_created_by_status" ON "lookup_classification_job" ("created_by", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_lookup_classification_job_org_status" ON "lookup_classification_job" ("organization_id", "status") `);
    }

}
