import { MigrationInterface, QueryRunner } from "typeorm";

export class ConsolidatedRebaseline202605271779906142530 implements MigrationInterface {
    name = 'ConsolidatedRebaseline202605271779906142530'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "public"."IDX_lookup_classification_job_created_by_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_lookup_classification_job_org_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_lookup_classification_job_status_created_at"`);
        await queryRunner.query(`CREATE TABLE "query_builder_templates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid, "name" character varying(120) NOT NULL, "description" text, "input" jsonb NOT NULL, "created_by" character varying(200) NOT NULL DEFAULT 'system', "updated_by" character varying(200) NOT NULL DEFAULT 'system', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8bc783b1902c39c17fcfab0e3c3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_095b60f432284184a80f6999f0" ON "query_builder_templates" ("organization_id", "name") `);
        await queryRunner.query(`CREATE TABLE "rule_review_alerts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "rule_id" character varying(200) NOT NULL, "card_key" character varying(200) NOT NULL, "previous_hash" character varying(64), "new_hash" character varying(64) NOT NULL, "diff_summary" text, "ai_advisory_json" jsonb, "status" character varying(16) NOT NULL DEFAULT 'open', "resolved_by" character varying(200), "resolution_note" text, "resolution_pr_url" text, "resolved_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6b7ebae16a7b578932e767c9fad" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7b0bad5a6de29a3ca2755cc140" ON "rule_review_alerts" ("status", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_99a4f46845d1a2bda8dd96d26b" ON "rule_review_alerts" ("card_key") `);
        await queryRunner.query(`CREATE INDEX "IDX_1140cb3e0074ed37a01f55e7fa" ON "rule_review_alerts" ("rule_id", "status") `);
        await queryRunner.query(`CREATE TABLE "knowledge_sources" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(180) NOT NULL, "publisher" character varying(120), "source_type" character varying(32) NOT NULL DEFAULT 'rss', "url" text NOT NULL, "jurisdiction" character varying(8), "document_type" character varying(50), "category" character varying(64), "trust_tier" character varying(32) NOT NULL DEFAULT 'official', "status" character varying(16) NOT NULL DEFAULT 'active', "crawl_frequency_hours" integer NOT NULL DEFAULT '6', "item_limit" integer NOT NULL DEFAULT '25', "priority" integer NOT NULL DEFAULT '100', "respect_robots" boolean NOT NULL DEFAULT true, "requires_review" boolean NOT NULL DEFAULT true, "metadata" jsonb, "last_crawled_at" TIMESTAMP WITH TIME ZONE, "last_success_at" TIMESTAMP WITH TIME ZONE, "last_failure_at" TIMESTAMP WITH TIME ZONE, "last_discovered_at" TIMESTAMP WITH TIME ZONE, "last_error_message" text, "created_by" character varying(200) NOT NULL DEFAULT 'system', "updated_by" character varying(200) NOT NULL DEFAULT 'system', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d92b58df209366bc2a9cc542581" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0b8632976aee387a49ba58eb4f" ON "knowledge_sources" ("priority", "name") `);
        await queryRunner.query(`CREATE INDEX "IDX_cb60f4d9fa051bc0115810ecaa" ON "knowledge_sources" ("publisher") `);
        await queryRunner.query(`CREATE INDEX "IDX_1f1b6e0cb0e348808308b384f2" ON "knowledge_sources" ("jurisdiction", "document_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_0304007b7e55c7e1db5ba7adb7" ON "knowledge_sources" ("status", "source_type") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_2e7f8a157608ddce99e70e83a5" ON "knowledge_sources" ("url") `);
        await queryRunner.query(`CREATE TABLE "knowledge_source_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "source_id" uuid NOT NULL, "url" text NOT NULL, "title" text, "published_at" TIMESTAMP WITH TIME ZONE, "status" character varying(24) NOT NULL DEFAULT 'discovered', "knowledge_card_id" uuid, "content_hash" character varying(64), "first_seen_at" TIMESTAMP WITH TIME ZONE, "last_seen_at" TIMESTAMP WITH TIME ZONE, "last_ingested_at" TIMESTAMP WITH TIME ZONE, "error_message" text, "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_19edca5335160bbefe283bb5a9c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2235d75a2565f54d9ceb8bedd4" ON "knowledge_source_items" ("last_seen_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_76bdfc70fb14290d288c618e9d" ON "knowledge_source_items" ("published_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_b680a8159940701b401601686f" ON "knowledge_source_items" ("content_hash") `);
        await queryRunner.query(`CREATE INDEX "IDX_af3e20a1b2c3151f39888e82de" ON "knowledge_source_items" ("source_id", "status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_knowledge_source_items_source_url" ON "knowledge_source_items" ("source_id", "url") `);
        await queryRunner.query(`CREATE TABLE "knowledge_source_crawl_runs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "source_id" uuid, "status" character varying(24) NOT NULL DEFAULT 'running', "trigger" character varying(80), "job_id" character varying(120), "attempted_items" integer NOT NULL DEFAULT '0', "succeeded_items" integer NOT NULL DEFAULT '0', "failed_items" integer NOT NULL DEFAULT '0', "result_json" jsonb, "error_message" text, "started_at" TIMESTAMP NOT NULL DEFAULT now(), "finished_at" TIMESTAMP WITH TIME ZONE, "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_51109f876fb085091a0ba738355" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_eaf83b0c9b5e3a3abc6a8b4fc9" ON "knowledge_source_crawl_runs" ("job_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e8cce406635ca00d24125ba7b7" ON "knowledge_source_crawl_runs" ("status", "started_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_39d8b00ae3a7d32b4f5b653877" ON "knowledge_source_crawl_runs" ("source_id", "started_at") `);
        await queryRunner.query(`CREATE TABLE "knowledge_cards" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "card_key" character varying(200) NOT NULL, "document_type" character varying(50) NOT NULL, "jurisdiction" character varying(8), "source_url" text, "content_hash" character varying(64) NOT NULL, "storage_ref" text, "payload" jsonb NOT NULL, "status" character varying(32) NOT NULL DEFAULT 'pending_ingest', "error_message" text, "effective_date" TIMESTAMP WITH TIME ZONE, "expiration_date" TIMESTAMP WITH TIME ZONE, "embedding" vector(1024), "embedding_openai" vector(1536), "ingested_by" character varying(200) NOT NULL DEFAULT 'system', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a5d07efab90482d7bd095c35bc7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6e15fe5e2ab942e5f73cae0dfd" ON "knowledge_cards" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_3f43690c46c12359b04bd5329d" ON "knowledge_cards" ("content_hash") `);
        await queryRunner.query(`CREATE INDEX "IDX_0cefab02191f8798ed3e4c7c77" ON "knowledge_cards" ("card_key", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_9e8a5679a872e1f8106a2fd458" ON "knowledge_cards" ("card_key") `);
        await queryRunner.query(`CREATE TABLE "cbam_quarterly_settlements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "quarter" character varying(8) NOT NULL, "quote_id" character varying(100) NOT NULL, "hts_code" character varying(20) NOT NULL, "sector" character varying(32) NOT NULL, "default_applied" boolean NOT NULL DEFAULT true, "cbam_certificates" numeric(18,6) NOT NULL, "provisional_cost_eur" numeric(18,4) NOT NULL, "observed_at" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_124621e0ec40f3edae5ce21c1bf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c44fe31a47022abbaa767c65ed" ON "cbam_quarterly_settlements" ("observed_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_14e955477640653dc5d004c72d" ON "cbam_quarterly_settlements" ("quote_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_0690628d001d1c3c4d7507747c" ON "cbam_quarterly_settlements" ("quarter", "sector") `);
        await queryRunner.query(`CREATE INDEX "IDX_09414fff700d6cd49dc7f338b4" ON "cbam_quarterly_settlements" ("quarter") `);
        await queryRunner.query(`CREATE TABLE "rule_status" ("rule_id" character varying(200) NOT NULL, "enabled" boolean NOT NULL DEFAULT true, "effective_from" TIMESTAMP WITH TIME ZONE, "effective_to" TIMESTAMP WITH TIME ZONE, "reason" text, "changed_by" character varying(200) NOT NULL, "changed_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3a71016dd3d722b7892ccf9a3e0" PRIMARY KEY ("rule_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_11413067841b1806fc3d7cbb75" ON "rule_status" ("effective_to") `);
        await queryRunner.query(`CREATE INDEX "IDX_cfb91ba21a5010a560e7b5f601" ON "rule_status" ("effective_from") `);
        await queryRunner.query(`CREATE TABLE "rule_status_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "rule_id" character varying(200) NOT NULL, "previous_enabled" boolean, "new_enabled" boolean NOT NULL, "previous_effective_from" TIMESTAMP WITH TIME ZONE, "previous_effective_to" TIMESTAMP WITH TIME ZONE, "new_effective_from" TIMESTAMP WITH TIME ZONE, "new_effective_to" TIMESTAMP WITH TIME ZONE, "reason" text, "changed_by" character varying(200) NOT NULL, "changed_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_266b890dfef322c91466d425ecc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d10af81c42c1ff012c85b48b01" ON "rule_status_history" ("changed_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_19591ddbfdaccee2cc4e9c76c0" ON "rule_status_history" ("rule_id", "changed_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_ce2898afd8abd533fec2e60bd6" ON "rule_status_history" ("rule_id") `);
        await queryRunner.query(`CREATE TABLE "ad_cvd_orders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "destination_country" character varying(4) NOT NULL, "hts_code" character varying(20) NOT NULL, "origin_country" character varying(4) NOT NULL, "exporter_name" character varying(200), "order_case_number" character varying(50) NOT NULL, "order_type" character varying(16) NOT NULL, "cash_deposit_rate" numeric(8,6) NOT NULL, "effective_from" TIMESTAMP WITH TIME ZONE NOT NULL, "effective_to" TIMESTAMP WITH TIME ZONE, "source" character varying(200) NOT NULL, "description" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_78f1b6d1ffea89e1bc205b46bd4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f99cf59a03fa232db134d4991b" ON "ad_cvd_orders" ("order_case_number") `);
        await queryRunner.query(`CREATE INDEX "IDX_5d1d06702eec5e44f93a231c75" ON "ad_cvd_orders" ("destination_country", "origin_country") `);
        await queryRunner.query(`CREATE INDEX "IDX_22492098bd9543b79ff71b1856" ON "ad_cvd_orders" ("destination_country", "hts_code") `);
        await queryRunner.query(`CREATE TABLE "ecommerce_handoffs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "platform" character varying(32) NOT NULL, "external_order_id" character varying(120) NOT NULL, "external_store_id" character varying(255), "state" character varying(32) NOT NULL DEFAULT 'broker_review_required', "origin_country" character varying(8) NOT NULL, "destination_country" character varying(8) NOT NULL, "port_of_entry" character varying(12), "items" jsonb NOT NULL, "shipment_value" numeric(14,2), "shipment_currency" character varying(8), "marketplace_request_id" uuid, "writeback_status" jsonb, "metadata" jsonb, "created_by" character varying(200) NOT NULL DEFAULT 'system', "updated_by" character varying(200) NOT NULL DEFAULT 'system', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b99656f209897072f0a2300db1d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3f8ae7afdd4a8c616e66ceebc7" ON "ecommerce_handoffs" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_80d0dd0b22acb29fb77e1de09e" ON "ecommerce_handoffs" ("organization_id", "state") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_5904ab61b895331882ba691a84" ON "ecommerce_handoffs" ("organization_id", "platform", "external_order_id") `);
        await queryRunner.query(`CREATE TABLE "data_transformer_runs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "profile_id" uuid NOT NULL, "status" character varying(24) NOT NULL DEFAULT 'pending', "input_row_count" integer NOT NULL DEFAULT '0', "output_row_count" integer NOT NULL DEFAULT '0', "issue_count" integer NOT NULL DEFAULT '0', "output" jsonb, "error_message" text, "triggered_by" character varying(200) NOT NULL DEFAULT 'system', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_17f29af1d4be2b278fbd18f95dc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2e71130464b68c86d06e48bd1a" ON "data_transformer_runs" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_b7e82dcef25957b80a284a9aa6" ON "data_transformer_runs" ("profile_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_f02ec0b21b543cfa7f18b1a68e" ON "data_transformer_runs" ("organization_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "data_transformer_run_issues" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "run_id" uuid NOT NULL, "severity" character varying(16) NOT NULL, "row_index" integer, "field" character varying(200), "message" text NOT NULL, "context" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_727747691a121a24353756d33b4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c0a39b7ba3706c2f4d76eecada" ON "data_transformer_run_issues" ("run_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_5c75867c1a0615ab28e89b3cad" ON "data_transformer_run_issues" ("run_id", "severity") `);
        await queryRunner.query(`CREATE TABLE "data_transformer_profiles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "name" character varying(120) NOT NULL, "description" text, "input_kind" character varying(32) NOT NULL, "output_kind" character varying(32) NOT NULL, "input_schema" jsonb NOT NULL, "defaults" jsonb NOT NULL DEFAULT '{}', "created_by" character varying(200) NOT NULL DEFAULT 'system', "updated_by" character varying(200) NOT NULL DEFAULT 'system', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_54be9e077510572d94b283e3d58" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ddd1c29b2c35051ce5068d4932" ON "data_transformer_profiles" ("organization_id", "input_kind") `);
        await queryRunner.query(`CREATE INDEX "IDX_3bd4908a96a11a24635f25a3b2" ON "data_transformer_profiles" ("organization_id", "name") `);
        await queryRunner.query(`CREATE TABLE "data_transformer_mappings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "profile_id" uuid NOT NULL, "source_field" character varying(200) NOT NULL, "target_field" character varying(200) NOT NULL, "transform" jsonb, "required" boolean NOT NULL DEFAULT false, "notes" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2078e1bad2ecf14e0104a5c9dad" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7f7876fe6694d8804433be6cd5" ON "data_transformer_mappings" ("profile_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e0a63c57ed318861cced3ab954" ON "data_transformer_mappings" ("profile_id", "target_field") `);
        await queryRunner.query(`CREATE TABLE "fx_records" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "quote_id" character varying(100) NOT NULL, "from_currency" character varying(3) NOT NULL, "to_currency" character varying(3) NOT NULL, "rate" numeric(18,8) NOT NULL, "provider" character varying(50) NOT NULL DEFAULT 'unknown', "observed_at" character varying(32) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c056e2cf7f1f5ff99350a1890ae" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2e25cfc2937109311ddba44f91" ON "fx_records" ("quote_id", "observed_at") `);
        await queryRunner.query(`CREATE TABLE "broker_outreach_leads" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "company_name" character varying(255) NOT NULL, "source_provider" character varying(32) NOT NULL DEFAULT 'manual', "source_external_id" character varying(255), "business_category" character varying(120), "website_url" character varying(500), "domain" character varying(255), "contact_email" character varying(255), "contact_phone" character varying(60), "country" character varying(80), "region" character varying(120), "city" character varying(120), "address" text, "latitude" numeric(10,7), "longitude" numeric(10,7), "status" character varying(24) NOT NULL DEFAULT 'new', "score" numeric(5,2) NOT NULL DEFAULT '0', "tags" jsonb NOT NULL DEFAULT '[]', "metadata" jsonb, "last_imported_at" TIMESTAMP WITH TIME ZONE, "last_contacted_at" TIMESTAMP WITH TIME ZONE, "converted_at" TIMESTAMP WITH TIME ZONE, "created_by" character varying(200) NOT NULL DEFAULT 'system', "updated_by" character varying(200) NOT NULL DEFAULT 'system', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_28070cf7ec1cb1466dcad4844e1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9a54923e5611a77cb8384542cb" ON "broker_outreach_leads" ("domain") `);
        await queryRunner.query(`CREATE INDEX "IDX_e30f6c2f146a32e83c95c9060e" ON "broker_outreach_leads" ("country", "business_category") `);
        await queryRunner.query(`CREATE INDEX "IDX_2b9784c31cc0f0222d0a30ccc1" ON "broker_outreach_leads" ("status", "created_at") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_5f7bbf6d3d0f00cb370490c6b4" ON "broker_outreach_leads" ("source_provider", "source_external_id") `);
        await queryRunner.query(`CREATE TABLE "broker_outreach_campaigns" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(180) NOT NULL, "status" character varying(24) NOT NULL DEFAULT 'draft', "audience" text, "objective" text, "email_subject" character varying(255), "email_body" text, "ai_prompt" text, "metrics" jsonb, "metadata" jsonb, "created_by" character varying(200) NOT NULL DEFAULT 'system', "updated_by" character varying(200) NOT NULL DEFAULT 'system', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_dbb277e9c2934dce78e2e98284c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7083d628e434e667afc3cfc08a" ON "broker_outreach_campaigns" ("status", "created_at") `);
        await queryRunner.query(`CREATE TABLE "broker_outreach_invites" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "lead_id" uuid NOT NULL, "campaign_id" uuid, "email" character varying(255) NOT NULL, "token_hash" character varying(64) NOT NULL, "status" character varying(24) NOT NULL DEFAULT 'created', "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "sent_at" TIMESTAMP WITH TIME ZONE, "opened_at" TIMESTAMP WITH TIME ZONE, "claimed_at" TIMESTAMP WITH TIME ZONE, "claimed_organization_id" uuid, "claimed_user_id" uuid, "metadata" jsonb, "created_by" character varying(200) NOT NULL DEFAULT 'system', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2cc19d779628c140ef31de98e9c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_93fc4ab69262b538a28d6b3b66" ON "broker_outreach_invites" ("status", "expires_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_114ba73a858890e32267b512aa" ON "broker_outreach_invites" ("campaign_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_ef8afbbf3719cc140da3517388" ON "broker_outreach_invites" ("lead_id", "status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b3c2ff7219e0353fc23cdc678b" ON "broker_outreach_invites" ("token_hash") `);
        await queryRunner.query(`CREATE TABLE "broker_outreach_discovery_runs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "provider" character varying(32) NOT NULL, "status" character varying(24) NOT NULL DEFAULT 'pending', "input" jsonb NOT NULL, "fetched_count" integer NOT NULL DEFAULT '0', "inserted_count" integer NOT NULL DEFAULT '0', "updated_count" integer NOT NULL DEFAULT '0', "failed_count" integer NOT NULL DEFAULT '0', "error_message" text, "triggered_by" character varying(200) NOT NULL, "job_id" character varying(120), "started_at" TIMESTAMP WITH TIME ZONE, "completed_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a398d787eb190684cbb879b4849" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_75aaec60df61f26c9fb52a5cf5" ON "broker_outreach_discovery_runs" ("status", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_afe6df6cc566419fdc26b63553" ON "broker_outreach_discovery_runs" ("provider", "created_at") `);
        await queryRunner.query(`CREATE TABLE "broker_outreach_discovery_results" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "run_id" uuid NOT NULL, "status" character varying(24) NOT NULL DEFAULT 'ingested', "external_id" character varying(255), "company_name" character varying(255), "website_url" character varying(500), "lead_id" uuid, "payload" jsonb, "error_message" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_527e8a311c342a7c5e5ee7c5400" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2626a637fe3066a2aeb131907e" ON "broker_outreach_discovery_results" ("lead_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_6b0c9330a9c616b3b30b92aa41" ON "broker_outreach_discovery_results" ("run_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_8f86beee4c5f4b11d43cee69d9" ON "broker_outreach_discovery_results" ("run_id", "created_at") `);
        await queryRunner.query(`ALTER TABLE "marketplace_broker_profiles" DROP COLUMN "office_address"`);
        await queryRunner.query(`ALTER TABLE "marketplace_broker_profiles" DROP COLUMN "contact_email"`);
        await queryRunner.query(`ALTER TABLE "marketplace_broker_profiles" DROP COLUMN "contact_phone"`);
        await queryRunner.query(`ALTER TABLE "calculation_history" ADD "audit" jsonb`);
        await queryRunner.query(`ALTER TABLE "marketplace_broker_profiles" ADD "contact_email_enc" jsonb`);
        await queryRunner.query(`ALTER TABLE "marketplace_broker_profiles" ADD "contact_phone_enc" jsonb`);
        await queryRunner.query(`ALTER TABLE "marketplace_broker_profiles" ADD "public_contact_exposure" character varying(24) NOT NULL DEFAULT 'platform_only'`);
        await queryRunner.query(`ALTER TABLE "marketplace_broker_profiles" ADD "office_address_enc" jsonb`);
        await queryRunner.query(`ALTER TABLE "tax_rules" ADD "tax_base_formula" character varying(32) NOT NULL DEFAULT 'GOODS_VALUE'`);
        await queryRunner.query(`ALTER TABLE "jurisdictions" ADD "country_state" character varying(24) NOT NULL DEFAULT 'PRODUCTION'`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_marketplace_quotes_one_accepted_per_request" ON "marketplace_quotes" ("request_id") WHERE status = 'accepted'`);
        await queryRunner.query(`ALTER TABLE "knowledge_source_items" ADD CONSTRAINT "FK_03d0894e3f937bf32fc19fc0bb2" FOREIGN KEY ("source_id") REFERENCES "knowledge_sources"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "knowledge_source_crawl_runs" ADD CONSTRAINT "FK_75af710b66b49a81127e75293c9" FOREIGN KEY ("source_id") REFERENCES "knowledge_sources"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "broker_outreach_invites" ADD CONSTRAINT "FK_d433f7a70dccafd5879d5249f3d" FOREIGN KEY ("lead_id") REFERENCES "broker_outreach_leads"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "broker_outreach_invites" ADD CONSTRAINT "FK_cf431fdb862c4ca846c11a64ea7" FOREIGN KEY ("campaign_id") REFERENCES "broker_outreach_campaigns"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "broker_outreach_invites" DROP CONSTRAINT "FK_cf431fdb862c4ca846c11a64ea7"`);
        await queryRunner.query(`ALTER TABLE "broker_outreach_invites" DROP CONSTRAINT "FK_d433f7a70dccafd5879d5249f3d"`);
        await queryRunner.query(`ALTER TABLE "knowledge_source_crawl_runs" DROP CONSTRAINT "FK_75af710b66b49a81127e75293c9"`);
        await queryRunner.query(`ALTER TABLE "knowledge_source_items" DROP CONSTRAINT "FK_03d0894e3f937bf32fc19fc0bb2"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_marketplace_quotes_one_accepted_per_request"`);
        await queryRunner.query(`ALTER TABLE "jurisdictions" DROP COLUMN "country_state"`);
        await queryRunner.query(`ALTER TABLE "tax_rules" DROP COLUMN "tax_base_formula"`);
        await queryRunner.query(`ALTER TABLE "marketplace_broker_profiles" DROP COLUMN "office_address_enc"`);
        await queryRunner.query(`ALTER TABLE "marketplace_broker_profiles" DROP COLUMN "public_contact_exposure"`);
        await queryRunner.query(`ALTER TABLE "marketplace_broker_profiles" DROP COLUMN "contact_phone_enc"`);
        await queryRunner.query(`ALTER TABLE "marketplace_broker_profiles" DROP COLUMN "contact_email_enc"`);
        await queryRunner.query(`ALTER TABLE "calculation_history" DROP COLUMN "audit"`);
        await queryRunner.query(`ALTER TABLE "marketplace_broker_profiles" ADD "contact_phone" character varying(60)`);
        await queryRunner.query(`ALTER TABLE "marketplace_broker_profiles" ADD "contact_email" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "marketplace_broker_profiles" ADD "office_address" jsonb`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8f86beee4c5f4b11d43cee69d9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6b0c9330a9c616b3b30b92aa41"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2626a637fe3066a2aeb131907e"`);
        await queryRunner.query(`DROP TABLE "broker_outreach_discovery_results"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_afe6df6cc566419fdc26b63553"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_75aaec60df61f26c9fb52a5cf5"`);
        await queryRunner.query(`DROP TABLE "broker_outreach_discovery_runs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b3c2ff7219e0353fc23cdc678b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ef8afbbf3719cc140da3517388"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_114ba73a858890e32267b512aa"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_93fc4ab69262b538a28d6b3b66"`);
        await queryRunner.query(`DROP TABLE "broker_outreach_invites"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7083d628e434e667afc3cfc08a"`);
        await queryRunner.query(`DROP TABLE "broker_outreach_campaigns"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5f7bbf6d3d0f00cb370490c6b4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2b9784c31cc0f0222d0a30ccc1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e30f6c2f146a32e83c95c9060e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9a54923e5611a77cb8384542cb"`);
        await queryRunner.query(`DROP TABLE "broker_outreach_leads"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2e25cfc2937109311ddba44f91"`);
        await queryRunner.query(`DROP TABLE "fx_records"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e0a63c57ed318861cced3ab954"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7f7876fe6694d8804433be6cd5"`);
        await queryRunner.query(`DROP TABLE "data_transformer_mappings"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3bd4908a96a11a24635f25a3b2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ddd1c29b2c35051ce5068d4932"`);
        await queryRunner.query(`DROP TABLE "data_transformer_profiles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5c75867c1a0615ab28e89b3cad"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c0a39b7ba3706c2f4d76eecada"`);
        await queryRunner.query(`DROP TABLE "data_transformer_run_issues"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f02ec0b21b543cfa7f18b1a68e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b7e82dcef25957b80a284a9aa6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2e71130464b68c86d06e48bd1a"`);
        await queryRunner.query(`DROP TABLE "data_transformer_runs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5904ab61b895331882ba691a84"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_80d0dd0b22acb29fb77e1de09e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3f8ae7afdd4a8c616e66ceebc7"`);
        await queryRunner.query(`DROP TABLE "ecommerce_handoffs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_22492098bd9543b79ff71b1856"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5d1d06702eec5e44f93a231c75"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f99cf59a03fa232db134d4991b"`);
        await queryRunner.query(`DROP TABLE "ad_cvd_orders"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ce2898afd8abd533fec2e60bd6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_19591ddbfdaccee2cc4e9c76c0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d10af81c42c1ff012c85b48b01"`);
        await queryRunner.query(`DROP TABLE "rule_status_history"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cfb91ba21a5010a560e7b5f601"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_11413067841b1806fc3d7cbb75"`);
        await queryRunner.query(`DROP TABLE "rule_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_09414fff700d6cd49dc7f338b4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0690628d001d1c3c4d7507747c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_14e955477640653dc5d004c72d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c44fe31a47022abbaa767c65ed"`);
        await queryRunner.query(`DROP TABLE "cbam_quarterly_settlements"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9e8a5679a872e1f8106a2fd458"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0cefab02191f8798ed3e4c7c77"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3f43690c46c12359b04bd5329d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6e15fe5e2ab942e5f73cae0dfd"`);
        await queryRunner.query(`DROP TABLE "knowledge_cards"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_39d8b00ae3a7d32b4f5b653877"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e8cce406635ca00d24125ba7b7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eaf83b0c9b5e3a3abc6a8b4fc9"`);
        await queryRunner.query(`DROP TABLE "knowledge_source_crawl_runs"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_knowledge_source_items_source_url"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_af3e20a1b2c3151f39888e82de"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b680a8159940701b401601686f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_76bdfc70fb14290d288c618e9d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2235d75a2565f54d9ceb8bedd4"`);
        await queryRunner.query(`DROP TABLE "knowledge_source_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2e7f8a157608ddce99e70e83a5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0304007b7e55c7e1db5ba7adb7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1f1b6e0cb0e348808308b384f2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cb60f4d9fa051bc0115810ecaa"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0b8632976aee387a49ba58eb4f"`);
        await queryRunner.query(`DROP TABLE "knowledge_sources"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1140cb3e0074ed37a01f55e7fa"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_99a4f46845d1a2bda8dd96d26b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7b0bad5a6de29a3ca2755cc140"`);
        await queryRunner.query(`DROP TABLE "rule_review_alerts"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_095b60f432284184a80f6999f0"`);
        await queryRunner.query(`DROP TABLE "query_builder_templates"`);
        await queryRunner.query(`CREATE INDEX "IDX_lookup_classification_job_status_created_at" ON "lookup_classification_job" ("created_at", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_lookup_classification_job_org_status" ON "lookup_classification_job" ("organization_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_lookup_classification_job_created_by_status" ON "lookup_classification_job" ("created_by", "status") `);
    }

}
