import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  CreateDateColumn,
  Index,
} from 'typeorm';

/**
 * Stores AI-generated consumer search query samples for each HTS leaf entry.
 * Used as ground-truth test data for search accuracy evaluation.
 * ~10 samples per HTS entry × ~17K leaf entries ≈ 170K total rows.
 */
@Entity('lookup_test_sample')
@Index(['htsNumber'])
export class LookupTestSampleEntity {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  /** 10-digit HTS leaf code, e.g. "3926.90.45.50" */
  @Column('varchar', { length: 20 })
  htsNumber: string;

  /** Consumer-language search query generated by AI */
  @Column('text')
  query: string;

  /** Model that generated this sample */
  @Column('varchar', { length: 50, default: 'claude-haiku' })
  source: string;

  @CreateDateColumn()
  createdAt: Date;
}
