import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import {
  HtsEntity,
  HtsEmbeddingEntity,
  HtsFormulaUpdateEntity,
  HtsFormulaCandidateEntity,
  HtsTestCaseEntity,
  HtsTestResultEntity,
  HtsImportHistoryEntity,
  HtsStageEntryEntity,
  HtsStageValidationIssueEntity,
  HtsStageDiffEntity,
  HtsSettingEntity,
  HtsExtraTaxEntity,
  CalculationHistoryEntity,
  ExternalProviderFormulaEntity,
  HtsTariffHistory2025Entity,
  HtsRepository,
  HtsProcessorService,
  FormulaGenerationService,
  HtsEmbeddingGenerationService,
  HtsFormulaUpdateService,
  HtsFormulaGenerationService,
  HtsChapter99FormulaService,
  HtsFormulaUpdateController,
} from '@hts/core';

@Module({
  imports: [
    TypeOrmModule.forFeature([
      HtsEntity,
      HtsEmbeddingEntity,
      HtsFormulaUpdateEntity,
      HtsFormulaCandidateEntity,
      HtsTestCaseEntity,
      HtsTestResultEntity,
      HtsImportHistoryEntity,
      HtsStageEntryEntity,
      HtsStageValidationIssueEntity,
      HtsStageDiffEntity,
      HtsSettingEntity,
      HtsExtraTaxEntity,
      CalculationHistoryEntity,
      ExternalProviderFormulaEntity,
      HtsTariffHistory2025Entity,
    ]),
  ],
  controllers: [HtsFormulaUpdateController],
  providers: [
    HtsRepository,
    HtsProcessorService,
    FormulaGenerationService,
    HtsEmbeddingGenerationService,
    HtsFormulaUpdateService,
    HtsFormulaGenerationService,
    HtsChapter99FormulaService,
  ],
  exports: [
    HtsRepository,
    HtsProcessorService,
    FormulaGenerationService,
    HtsEmbeddingGenerationService,
    HtsFormulaUpdateService,
    HtsFormulaGenerationService,
    HtsChapter99FormulaService,
  ],
})
export class CoreWrapperModule {}
